dataMiBS = [{
        title: '',
        sections: [{
            title: 'Od wydawcy',
            text: '<p>Oto trafia Wam do rąk jedna z tych książek, które wywarły największy wpływ na czytelników. Przedstawia ona sprawdzony plan prowadzący do zdobycia bogactwa. Wyjaśnia, jaki sposób zastosować ten plan w praktyce, poczynając od tej chwili, od dziś.</p><p>Co sprawia, że niektórzy ludzie idą przez życie przebojem, od sukcesu do sukcesu, pomnażając swe dochody i zyciowe szczęście - a inni nawet nie próbują o nie zabiegać?</p><p>Co sprawia, że ktoś uzyskuje poważne wpływy osobiste, a ktos inny pozostaje jednostką bez znaczenia? Co jest przyczyną powodującą, iż jeden człowiek znajduje wyjście z każdej sytuacji, toruje sobie drogę przez przeciwności życia, uzyskując spełnienie swych najdroższych marzeń - a drugi załamuje się, przegrywa, nie dochodzi do niczego?</p><p>Przed laty autor tej książki, Napoleon Hill, zasiadł do rozmowy z jednym spośród najbogatszych wówczas ludzi na świecie, Andrew Carnegiem, i zyskał odeń pierwszą zapowiedź wyjawienia tej wielkiej Tajemnicy. Carnegie zachęcił wtedy Hilla do badania, w jaki sposób inni ludzie z tej Tajemnicy korzystali, do studiowania ich metod posługiwania się nią - i do opracowania prostego planu wiodącego do zdobycia bogactwa, który można by przedstawić światu jako Plan Mistrzowski</p><p>MYŚL I BOGAĆ SIĘ ujawnia tę Tajemnicę i przedstawia ów Plan. Od pierwszego wydania tej książki w rokku 1937 ukazały się 42 kolejne edycje, drukowane w maksymalnym pośpiechu, jakiego wymagało zapotrzebowanie na nią. Wydanie niniejsze dostosowane jest do wymogów chwili obecnej, wyposażono je w specjalne udogodnienia w korzystaniu z tekstu książki, w tym także w krótkie wnioski zamykające każdy z jej rozdziałów, służące odświeżeniu treści danego rozdziału w pamięci.</p>Tak więc mamy nareszcie prostą, pewną drogę do pokonania wszelkich przeciwności, spełnienia wszelkich dążeń, zdobycia życiowego sukcesu. Książka ta wstrząśnie Tobą dzięki swej mocy dokonania w Twym życiu głębokiej przemiany. Zrozumiesz dzięki niej, dlaczego niektórzy ludzie dochodzą do wielkich pieniędzy i sukcesów życiowych - bo sam staniesz się jednym z nich.</p>'
        }, {
            title: 'Przedmowa',
            text: '<p>W każdym rozdziale tej książki omawiam jedną z przynoszących pieniądze tajemnic, które umożliwiły zdobycie fortuny setkom najbogatszych ludzi na świecie - ludziom, których dokonania życiowe analizowałem przez długie lata.</p><p>Na Tajemnicę ich sukcesu zwrócił mi uwagę przed ponad pół wiekiem Andrew Carnegie. Ten obrotny, miło w obejściu stary Szkot, cierpliwie wbijał mi ją do głowy, kiedy byłem jeszcze małym chłopcem. A potem osuwał się w głąb swego fotela i z błyskiem rozbawienia w oku sprawdzał, czy mam dość oleju w głowie, aby w pełni docenić to, co mi wyjawił.</p><p>A kiedy się już uepwnił, że pojąłem jego myśl, zapytał, czy byłbym gotów poświęcić jakieś dwadzieścia lat, albo i więcej, by się przygotować do przedstawienia tej myśli światu, kobietom i mężczyznom, którzy bez poznania tej myśli mogliby zaznać życiowej klęski. Odrzekłem, że się tego podejmę i oto, przy współpracy pana Carnegiego, dotrzymuję tego zobowiązania.</p><p>Książka niniejsza wyjawia tę tajemnicę, dowiedzoną doświadczeniem życiowym tysięcy ludzi z różnych dziedzin zycia. To właśnie od pana Carnegiego pochodzi pomysł, by ową magiczną formułę, która jemu samemu przyniosła wspaniały życiowy sukces, odnieść do dokonań ludzi, któ©zy nie mieli czasu zastanawiać się nad sposobem, w jakim dochodzi się do bogactwa; miał on też nadzieję, że będę mógł dowieść słuszności tej formuły, potwierdzonej doświadczeniem każdego z tych mężczyzn i każdej z tych kobiet. Pan Carnegie sądził, że jego teorię będzie się wykładało we wszystkich szkołach i wyrażał przekonanie, iż gdyby uczono jej w należyty sposób, zrewolucjonizowałaby cały system oświatowy w tak znacznym stopniu, że czas przeznaczony na kształcenie młodzieży można by zredukować do połowy.</p>',
            subsections: [{
                title: 'Autentyczne życiorysy dowodzą zadziwiającej siły Tajemnicy Sukcesu',
                text: '<p>W rozdziale III poświęconym Wierze w siebie znajdziecie zadziwiającą historię tworzenia gigantycznego koncernu United States Steel Corporation, powołanego do życia i kierowanego przez młodego człowieka, na którego przykładzie pan Carnegie dowodzi, iż jego teoria sprawdza się na <i>każdym człowieku, który ją przyjmie</i>. Wierne zastosowanie tej tajemnicy prziniosło Charlesowi M. Schwabowi ogromne pieniądze i wpływy. Mówiąc otwarcie, zastosowanie tej formuły przysporzyło panu Schwabowi <i>sześćset tysięcy dolarów</i>.</p>'
            }]
        }]
    }

]