let plan = {
    months: [{
        name: 'styczeń',
        motto: 'cechy charakteru',
        days: [{
            day: 1,
            motto: 'niezawodność jest fundamentem dobrego charakteru',
            description: 'Ludzie z charakterem robią to - co mówią, że zrobią, wtedy - kiedy mówią, że zrobią i zgodnie z ustalonymi warunkami. Są liderami, do których inni zwracają się o prowadzenie, ponieważ udowodnili, że zależy im i można im zaufać. Jeśli szanujesz siebie na tyle, by dotrzymywać zobowiązań nawet wtedy, gdy jest to dla ciebie niewygodne, inni również zaczną cię szanować.<br>Niezawodność, podobnie jak inne cechy charakteru, jest nawykiem. Zacznij dzisiaj - na początku nowego roku - kształtować postawę niezawodności. Jeśli odkładasz sprawy lub trudno ci dotrzymywać przyrzeczeń, rozpocznij od rzeczy drobnych. Obiecaj sobie, że na przykład będziesz punktualny i tak zorganizuj czas, by dotrzymać najbliższego terminu. wkrótce przekonasz się, że łatwiej ci będzie wypełniać inne zobowiązania.'
        }, {
            day: 2,
            motto: '',
            description: ''
        }, {
            day: 3,
            motto: '',
            description: ''
        }, {
            day: 4,
            motto: '',
            description: ''
        }, {
            day: 5,
            motto: '',
            description: ''
        }, {
            day: 6,
            motto: '',
            description: ''
        }, {
            day: 7,
            motto: '',
            description: ''
        }, {
            day: 8,
            motto: '',
            description: ''
        }, {
            day: 9,
            motto: '',
            description: ''
        }, {
            day: 10,
            motto: '',
            description: ''
        }, {
            day: 11,
            motto: '',
            description: ''
        }, {
            day: 12,
            motto: '',
            description: ''
        }, {
            day: 13,
            motto: '',
            description: ''
        }, {
            day: 14,
            motto: '',
            description: ''
        }, {
            day: 15,
            motto: '',
            description: ''
        }, {
            day: 16,
            motto: '',
            description: ''
        }, {
            day: 17,
            motto: '',
            description: ''
        }, {
            day: 18,
            motto: '',
            description: ''
        }, {
            day: 19,
            motto: '',
            description: ''
        }, {
            day: 20,
            motto: '',
            description: ''
        }, {
            day: 21,
            motto: '',
            description: ''
        }, {
            day: 22,
            motto: '',
            description: ''
        }, {
            day: 23,
            motto: '',
            description: ''
        }, {
            day: 24,
            motto: '',
            description: ''
        }, {
            day: 25,
            motto: '',
            description: ''
        }, {
            day: 26,
            motto: '',
            description: ''
        }, {
            day: 27,
            motto: '',
            description: ''
        }, {
            day: 28,
            motto: '',
            description: ''
        }, {
            day: 29,
            motto: '',
            description: ''
        }, {
            day: 30,
            motto: '',
            description: ''
        }, {
            day: 31,
            motto: '',
            description: ''
        }]
    }, {
        name: 'luty',
        motto: 'inicjatywa osobista',
        days: [{
            day: 1,
            motto: '',
            description: ''
        }, {
            day: 2,
            motto: '',
            description: ''
        }, {
            day: 3,
            motto: '',
            description: ''
        }, {
            day: 4,
            motto: '',
            description: ''
        }, {
            day: 5,
            motto: '',
            description: ''
        }, {
            day: 6,
            motto: '',
            description: ''
        }, {
            day: 7,
            motto: '',
            description: ''
        }, {
            day: 8,
            motto: '',
            description: ''
        }, {
            day: 9,
            motto: '',
            description: ''
        }, {
            day: 10,
            motto: '',
            description: ''
        }, {
            day: 11,
            motto: '',
            description: ''
        }, {
            day: 12,
            motto: '',
            description: ''
        }, {
            day: 13,
            motto: '',
            description: ''
        }, {
            day: 14,
            motto: '',
            description: ''
        }, {
            day: 15,
            motto: '',
            description: ''
        }, {
            day: 16,
            motto: '',
            description: ''
        }, {
            day: 17,
            motto: '',
            description: ''
        }, {
            day: 18,
            motto: '',
            description: ''
        }, {
            day: 19,
            motto: '',
            description: ''
        }, {
            day: 20,
            motto: '',
            description: ''
        }, {
            day: 21,
            motto: '',
            description: ''
        }, {
            day: 22,
            motto: '',
            description: ''
        }, {
            day: 23,
            motto: '',
            description: ''
        }, {
            day: 24,
            motto: '',
            description: ''
        }, {
            day: 25,
            motto: '',
            description: ''
        }, {
            day: 26,
            motto: '',
            description: ''
        }, {
            day: 27,
            motto: '',
            description: ''
        }, {
            day: 28,
            motto: '',
            description: ''
        }, {
            day: 29,
            motto: '',
            description: ''
        }, {
            day: 30,
            motto: '',
            description: ''
        }, {
            day: 31,
            motto: '',
            description: ''
        }]
    }, {
        name: 'marzec',
        motto: 'zwycięska postawa',
        days: [{
            day: 1,
            motto: '',
            description: ''
        }, {
            day: 2,
            motto: '',
            description: ''
        }, {
            day: 3,
            motto: '',
            description: ''
        }, {
            day: 4,
            motto: '',
            description: ''
        }, {
            day: 5,
            motto: '',
            description: ''
        }, {
            day: 6,
            motto: '',
            description: ''
        }, {
            day: 7,
            motto: '',
            description: ''
        }, {
            day: 8,
            motto: '',
            description: ''
        }, {
            day: 9,
            motto: '',
            description: ''
        }, {
            day: 10,
            motto: '',
            description: ''
        }, {
            day: 11,
            motto: '',
            description: ''
        }, {
            day: 12,
            motto: '',
            description: ''
        }, {
            day: 13,
            motto: '',
            description: ''
        }, {
            day: 14,
            motto: '',
            description: ''
        }, {
            day: 15,
            motto: '',
            description: ''
        }, {
            day: 16,
            motto: '',
            description: ''
        }, {
            day: 17,
            motto: '',
            description: ''
        }, {
            day: 18,
            motto: '',
            description: ''
        }, {
            day: 19,
            motto: '',
            description: ''
        }, {
            day: 20,
            motto: '',
            description: ''
        }, {
            day: 21,
            motto: '',
            description: ''
        }, {
            day: 22,
            motto: '',
            description: ''
        }, {
            day: 23,
            motto: '',
            description: ''
        }, {
            day: 24,
            motto: '',
            description: ''
        }, {
            day: 25,
            motto: '',
            description: ''
        }, {
            day: 26,
            motto: '',
            description: ''
        }, {
            day: 27,
            motto: '',
            description: ''
        }, {
            day: 28,
            motto: '',
            description: ''
        }, {
            day: 29,
            motto: '',
            description: ''
        }, {
            day: 30,
            motto: '',
            description: ''
        }, {
            day: 31,
            motto: '',
            description: ''
        }]
    }, {
        name: 'kwiecień',
        motto: 'wyznaczanie celów',
        days: [{
            day: 1,
            motto: '',
            description: ''
        }, {
            day: 2,
            motto: '',
            description: ''
        }, {
            day: 3,
            motto: '',
            description: ''
        }, {
            day: 4,
            motto: '',
            description: ''
        }, {
            day: 5,
            motto: '',
            description: ''
        }, {
            day: 6,
            motto: '',
            description: ''
        }, {
            day: 7,
            motto: '',
            description: ''
        }, {
            day: 8,
            motto: '',
            description: ''
        }, {
            day: 9,
            motto: '',
            description: ''
        }, {
            day: 10,
            motto: '',
            description: ''
        }, {
            day: 11,
            motto: '',
            description: ''
        }, {
            day: 12,
            motto: '',
            description: ''
        }, {
            day: 13,
            motto: '',
            description: ''
        }, {
            day: 14,
            motto: '',
            description: ''
        }, {
            day: 15,
            motto: '',
            description: ''
        }, {
            day: 16,
            motto: '',
            description: ''
        }, {
            day: 17,
            motto: '',
            description: ''
        }, {
            day: 18,
            motto: '',
            description: ''
        }, {
            day: 19,
            motto: '',
            description: ''
        }, {
            day: 20,
            motto: '',
            description: ''
        }, {
            day: 21,
            motto: '',
            description: ''
        }, {
            day: 22,
            motto: '',
            description: ''
        }, {
            day: 23,
            motto: '',
            description: ''
        }, {
            day: 24,
            motto: '',
            description: ''
        }, {
            day: 25,
            motto: '',
            description: ''
        }, {
            day: 26,
            motto: '',
            description: ''
        }, {
            day: 27,
            motto: '',
            description: ''
        }, {
            day: 28,
            motto: '',
            description: ''
        }, {
            day: 29,
            motto: '',
            description: ''
        }, {
            day: 30,
            motto: '',
            description: ''
        }, {
            day: 31,
            motto: '',
            description: ''
        }]
    }, {
        name: 'maj',
        motto: 'Działanie',
        days: [{
            day: 1,
            motto: '',
            description: ''
        }, {
            day: 2,
            motto: '',
            description: ''
        }, {
            day: 3,
            motto: '',
            description: ''
        }, {
            day: 4,
            motto: '',
            description: ''
        }, {
            day: 5,
            motto: '',
            description: ''
        }, {
            day: 6,
            motto: '',
            description: ''
        }, {
            day: 7,
            motto: '',
            description: ''
        }, {
            day: 8,
            motto: '',
            description: ''
        }, {
            day: 9,
            motto: '',
            description: ''
        }, {
            day: 10,
            motto: '',
            description: ''
        }, {
            day: 11,
            motto: '',
            description: ''
        }, {
            day: 12,
            motto: '',
            description: ''
        }, {
            day: 13,
            motto: '',
            description: ''
        }, {
            day: 14,
            motto: '',
            description: ''
        }, {
            day: 15,
            motto: '',
            description: ''
        }, {
            day: 16,
            motto: '',
            description: ''
        }, {
            day: 17,
            motto: '',
            description: ''
        }, {
            day: 18,
            motto: '',
            description: ''
        }, {
            day: 19,
            motto: '',
            description: ''
        }, {
            day: 20,
            motto: '',
            description: ''
        }, {
            day: 21,
            motto: '',
            description: ''
        }, {
            day: 22,
            motto: '',
            description: ''
        }, {
            day: 23,
            motto: '',
            description: ''
        }, {
            day: 24,
            motto: '',
            description: ''
        }, {
            day: 25,
            motto: '',
            description: ''
        }, {
            day: 26,
            motto: '',
            description: ''
        }, {
            day: 27,
            motto: '',
            description: ''
        }, {
            day: 28,
            motto: '',
            description: ''
        }, {
            day: 29,
            motto: '',
            description: ''
        }, {
            day: 30,
            motto: '',
            description: ''
        }, {
            day: 31,
            motto: '',
            description: ''
        }]
    }, {
        name: 'czerwiec',
        motto: 'Okazje',
        days: [{
            day: 1,
            motto: 'okazja ma dziwny sposób podkradania się do osoby, która potrafi ją rozpoznać i jest gotowa z niej skorzystać',
            description: 'Dziwnym kaprysem ludzkiej natury niektórzy z nas potrafią dostrzec okazje, podczas gdy inni widzą jedynie problemy. kKiedy trenujesz umysł w pposzukiwaniu sposobności, to przekonujesz się, że dosłownie każdy dzień przynosi więcej okazji, niż możesz wykożystać. Będą wszędzie wokół ciebie. Nie Ty będziesz wypatrywał, to one będą szukać ciebie. Największy problem stworzy wybór najlepszych.'
        }, {
            day: 2,
            motto: 'ci, którzy łatwo widzą swoje ograniczenia, zazwyczaj z trudem dostrzegają okazje',
            description: 'Producent filmowy, Michael Todd, powiedział kiedyś: "Być bez grosza to sytuacja chwilowa; być biednym to stan umysłu". Podobnie jest z okazjami. To, czy zauważasz sposobności czy ograniczenia, leży całkowicie w zasięgu twojej kontroli. Sposób postrzegania świata stanowi odbicie odbicie twojej postawy umysłowej. Jeżeli koncentrujesz się na swojej niezdatności - dręczą cię strach, wątpliwości i porażki, kiedy jednak skupiasz się swych mocnych stronach - odnajdujesz odwagę, pewność i sukces.<br>Pewność siebie może zastąpić powątpiewanie o sobie jedynie w wyniku celowego, zaplanowanego wysiłku. Kiedy zaczniesz wątpić w swoje umiejętności i zdolności, zatrzymaj się, by przejrzeć wcześniejsze dokonania. Zidentyfikuj każde doświadczenie, mogące pomóc w obecnej sytuacji. Gdy zastosujesz wiedzę i mądrość, jakie zgromadziłeś, niewiele pozostanie ograniczeń, których nie będziesz mógł pokonać.'
        }, {
            day: 3,
            motto: 'nie twierdz, że świat nie dał ci okazji',
            description: 'Okazje nigdy nie są tak zwyczajnie wręczane przez los; muszą zostać wykreowane. Dla wszystkich ludzi dowolny okres życia obfituje w okazje. Mogą się one nie mieścić w kręgu twych preferencji, ale każda wykorzystana sposobność prowadzi do większych i lepszych okazji. Ułomności fizyczne czy umysłowe mogą wymagać badania tetytorium nieznanego dla innych, jednak równocześnie oznacza to, że posiadasz sposobności, których pozostali nigdy nie odnajdą. Pomyśl o błyskotliwej rozprawie Stephena Hawkinga na temat natury wszechświata, mimo faktu że paraliż uniemożliwia mu pisanie i mówienie w takiej postaci, jaką my znamy.<br>Ci, którzy podchodzą do swojej pracy i kariery z entuzjazmem, zawsze znajdują mnóstwo okazji, podczas gdy ci, którzy narzekają, że nikt nie dał im nigdy szansy, są zaledwie obserwatorami życia. Kiedy postanowisz, że nie dasz nikomu decydować za ciebie o twojej przyszłości, kiedy odmawiasz chwilowym niepowodzeniom prawa do pokonania cię, twoim przeznaczeniem staje się wielki sukces. Sposobności będą na ciebie czekać.'
        }, {
            day: 4,
            motto: '',
            description: ''
        }, {
            day: 5,
            motto: '',
            description: ''
        }, {
            day: 6,
            motto: '',
            description: ''
        }, {
            day: 7,
            motto: '',
            description: ''
        }, {
            day: 8,
            motto: '',
            description: ''
        }, {
            day: 9,
            motto: '',
            description: ''
        }, {
            day: 10,
            motto: '',
            description: ''
        }, {
            day: 11,
            motto: '',
            description: ''
        }, {
            day: 12,
            motto: '',
            description: ''
        }, {
            day: 13,
            motto: '',
            description: ''
        }, {
            day: 14,
            motto: '',
            description: ''
        }, {
            day: 15,
            motto: '',
            description: ''
        }, {
            day: 16,
            motto: '',
            description: ''
        }, {
            day: 17,
            motto: '',
            description: ''
        }, {
            day: 18,
            motto: '',
            description: ''
        }, {
            day: 19,
            motto: '',
            description: ''
        }, {
            day: 20,
            motto: '',
            description: ''
        }, {
            day: 21,
            motto: '',
            description: ''
        }, {
            day: 22,
            motto: '',
            description: ''
        }, {
            day: 23,
            motto: '',
            description: ''
        }, {
            day: 24,
            motto: '',
            description: ''
        }, {
            day: 25,
            motto: 'pokaż mi, jak zaoszczędzić drobną kwotę na dowolnej operacji w fabryce, a pokażę ci, jak zdobyć szybki i odpowiedni awans',
            description: 'Kiedy poszukujesz sposobów zaoszczędzenia pieniędzy dla firmy, postępujesz jak kierownik lub właściciel. Każdy kierownik wart swej płacy wie, że w produkcji seryjnej zaoszczędzenie kilku groszy w dowolnym procesie szybko zsumuje się do milionów. A ktoś, kto wymyśli sposób na zaoszczędzenie przez firmę milionów jest "skazany na awans". Jest po prostu zbyt cenny, by nie awansował.<br>Najlepszą osobą, która może poprawić wydajność w twojej pracy, jesteś ty sam. Nikt inny nie zna jej tak dokładnie jak ty. Zachęć siebie do stałego ulepszania poprzez rywalizowanie z sobą samym. Wykonująć konkretne zadanie szukaj skrótów, które pozwolą ci ukończyć je szybciej. Czas, jaki zaoszczędzisz, wykorzystaj na przeanalizowanie innych części swej pracy, zgłoszenie się do pomocy przy trudnych czy czasochłonnych operacjach albo podjęcie się nowego, bardziej satysfakcjonującego zadania.'
        }, {
            day: 26,
            motto: 'wielu ludzi sukcesu w porażce i przeciwności odnalazło okazje, których nie rozpoznałoby w bardziej korzystnych okolicznościach',
            description: 'Samuel Johnson zauważył kiedyź, że perspektywa śmierci na szubienicy cudownie wyostrza umysł. prawdopodobnie mogłeś sam odkryć, że twój umysł wydaje się najbardziej bystry, kiedy mierzysz się z największymi trudnościami. Desperacja często dowodzi, że w rzeczywistości jesteś lepszy niż myslisz. Za wyjątkiem jednak bezpośredniego zagrożenia twojego życie czy zdrowia, mało jest sytuacji, które wymagają natychmiastowego działania. Kiedy świat zdaje się spiskować przeciw tobie i nic się nie udaje, przerwij na chwilę, aby przemyśleć sytuację - potem opracuj najbardziej odpowiedni plan działania, ten, który ma największe prawo powodzenia.'
        }, {
            day: 27,
            motto: 'nie przeoczaj drobnych szczegółów; pamiętaj, że wszechświat i wszystko, co się w nim znajduje, jest zbudowane z maleńkich atomów',
            description: 'Stare powiedzenie mówi: "Jeśli zadbasz o szczegóły, wielkie sprawy zatroszczą się same o siebie". Innymi słowy, każda praca składa się z małych detali, z których każdy, jeśli zostanie przeoczony, może stwarzać później wielkie problemy. Jeżeli masz kłopoty z radzeniem sobie ze szczegółami - robotą papierkową, księgowaniem rachunków i innymi nużącymi drobiazgami - w cyklu swej pracy wyznacz czas (dziennie, tygodniowo czy miesięcznie), by zająć się tymi mało pociągającymi czynnościami. Przygotuj się umysłowo do owych zadań, a może nawet uznasz, iż ta praca nie była ani trochę tak nieprzyjemna jak się spodziewałeś.'
        }, {
            day: 28,
            motto: 'twoja praca nie zrobi dla ciebie więcej, niż ty dla niej',
            description: 'Każda praca zawiera okazje do osobistego wzrostu, jeśli podchodzisz do niej jako do pozytywnego doświadczenia, które uczy. Podobnie jak każde przedsięwzięcie trzeba przystosować do nowych technologii, nowej konkurencjii i niezliczonych innych zmian, tak samo musi to robić każdy człowiek. Jeżeli w swojej pracy nie uczysz się i nie robisz postępów, to następuje stagnacja i zostajesz w tyle.<br>Nie można stać w miejscu. Patrz na każdy dzień jako na okazję nauczenia się czegoś nowego, udoskonalenia siebie, a potem zrób coś lepiej niż kiedykolwiek przedtem. W dynamicznej formie nie da się opanować po mistrzowsku każdego dnia. Właśnie wtedy, kiedy sądzisz że wszystko rozgryzłeś, rzeczy ulegają zmianie. Przyjmij takie zmiany jako konieczny aspekt biznesu, który czyni życie ciekawszym i pasjonującym. Uznasz swą pracę za znacznie przyjemniejszą. kiedy tak postąpisz i naprawdę przekonaz się, że robi ona dla ciebie więcej niż ty dla niej.'
        }, {
            day: 29,
            motto: 'zdolności są czymś wspanilszym od pieniędzy, ponieważ nie mogą zostać zgubione ani skradzione',
            description: 'Kiedy studiujesz życie ludzi, którzy odnieśli bardzo duży sukces, spostrzeżesz, że rzadko wspinnają się na szczyt i pozostają tam. Często kilka razy podczas swojej kariery wdrapują się na wierzchołek i spadają na dno, wiedzą jednak, iż to, co wyniosło ich tam, gdzie byli - ich zdolności - istnieje nadal, by pomóc im raz jeszcze sięgnąć szczytu.<br>Twoje umiejętności to jedyna rzecz, którą masz na swoją wyłączną własność; nikt nigdy nie może cię ich pozbawić.'
        }, {
            day: 30,
            motto: 'kiedy zamykasz drzwi swego umysłu przed negatywnymi myślami, otwierają się przed tobą bramy okazji',
            description: 'Naturą wszystkich okazji jest to, że po prostu nie chcą przyłączać się do negatywnych myślicieli. Negatywne umysły nie potrafią wymyślić pasjonujących nowych przedsięwzięć, wynaleźć nowych produktów, rozwinąć trudnych problemów ani też stworzyć pięknej muzyki czy dzieła sztuki. wszystkie te formy aktywności wymagają pozytywnej wiary w siebie i swoje zdolności.<br>Kiedy do każdego wyzwania podchodzisz z pozytywną postawą umysłową, zawsze odkryjesz okazje, które inni przeoczyli. Rozkoszuj się swymi osiągnięciami, smakuj je i przypominaj sobie o nich, kiedy droga staje się trudna. Czerp otuchę i pocieszenie ze świadomości, że powiodło ci się w przeszłości i że może tak być ponownie. <b>Możes to zrobić, jeżli myślisz, że możesz!</b>'
        }]
    }, {
        name: 'lipiec',
        motto: 'moc pracy zespołowej',
        days: [{
            day: 1,
            motto: 'jeśli nie jesteś oficerem w wojsku, lepsze rezultaty uzyskasz prosząc niż rozkazując',
            description: 'Armie spędzają niezliczone godziny na ćwiczeniu ludzi w wykonywaniu rozkazów bez zadawania pytań. W przypadku żołnieża to ważna zaleta. Jednak w życiu codziennym sprawy nie funkcjonują w taki sposób. Liderzy w biznesie, polityce i samorządzie wiedzą, że zwykli ludzie będą dokonywać wyjątkowych dzieł, kiedy zostaną o to poproszeni - a nie kiedy rozkaże im się to zrobić.<br>Nawet kierując ludźmi, uzyskasz znacznie więcej, kiedy zastąpisz każde polecenie prośbą. Zwroty grzecznościowe takie jak: Czy zechciałbyć... albo czy mógłbym prosić o pańską pomoc w... czy też zawsze skuteczne Proszę... znacznie częściej przyniosą dobry skutek, niż onieśmielanie tych, którzy dla ciebie pracują. Kiedy zaś potrzebujesz pomocy ze stronyc tych, na których pensję nie masz wpływu, przekonasz się, że także dużo lepiej reagują na prośby niż polecenia.'
        }, {
            day: 2,
            motto: 'nikt nie jest zdolny do wydawania poleceń, dopóki sam nie nauczy się, jak przyjmować i wykonywać instrukcje',
            description: 'Istotną zaletą przywództwa jest rozwijanie zdolności przekonywania innych, aby wiązali swoje cele z twoimi i z celami firmy. Dopóki ty sam nie jesteś w stanie połączyć sił z innymi w dążeniu do wspólnego celu, nigdy nie przekonasz innych, aby przyłączyli się do twego. Skuteczni liderzy uznają wartość wspólnej pracy i uczą się, jak wykonywać instrukcje, zanim przyjmą odpowiedzialość za postępowanie innych.<br>Dobrzy przywódcy pokazują swoim przykładem, jakiego postępowania oczekują od innych. Nawet jeśli oddziały wojskowe są wyszkolone do niekwestionowanego wykonywania rozkazów, to i tak oficer prowadzi ich do walki. Nie możesz innych popychać, by naśladowali twój przykład; musisz pociągnąć ich za sobą. Kiedy poprzez każde swoje słowo i czyn udowadniasz, że jesteś człowiekiem z charakterem, który pracuje dla wyższego dobra całej instytucji, twoi ludzie podążą za tobą.'
        }, {
            day: 3,
            motto: 'chętna współpraca wytwarza trwałą moc, podczas gdy wymuszona kończy się klęską',
            description: 'Nigdy nie przetrwała żadna cywilizacja oparta o niesprawiedliwe traktowanie ludzi. Tyran może wymusić współpracę przez jakiś czas, ale tego rodzaju siła nigdy nie jest długotrwała. Tylko wtedy, kiedy ludzi obdarza się szacunkiem, na jakizasługują, chętnie stwarzają i utrzymują udane instytucje i społeczeństwa. Budując firmę czy organizację opartą na zasadach uczciwości i sprawiedliwości w stosunku do każdego członka, inicjujesz siłę, która długo przetrwa.<br>Najlepszym sposobem zapewnienia sobie zaangażowania i nie ustającej współpracy jest zwyczajne stosowanie złotej reguły. To najbardziej udana i trwała teoria zarządzania, jaką kiedykolwiek wymyślono. Kiedy traktujesz innych tak, jak chciałbyś być traktowany będąc na ich miejscu, zachęcasz do lojalności i entuzjastycznej współpracy. Wyznaczaj wysokie normy dla siebie i innych, traktuj ich dobrze, pozwól im wykonywać ich zajęcia, a będą dla ciebie dokonywać cudów.'
        }, {
            day: 4,
            motto: 'staraj się mówić swojemu szefowi o tym, co lubisz, a przekonasz się, jak chętnie pomoże ci pozbyć się tego, co ci nie odpowiada',
            description: 'W ostatnich latach poczyniono wielki postępy w przezwyciężaniu tradycyjnych animozji pomiędzy pracownikami i szefami. Wreszcie dotarło do nas, że kiedy skupiamy się na lepszym obsługiwaniu klientów i kontrachentów, wszyscy wygrywają. Gdy zaczniesz się koncentrować na tym, co ci się nie podoba, zdziwi cię, jak szybko zostanie ci powierzona większa odpowiedzialność i będziesz mógł uczyć swycj pracowników wykonywania twojej wcześniejszej pracy.'
        }, {
            day: 5,
            motto: 'na dowolnym rynku przyjazna współpraca zdobędzie dla ciebie znacznie więcej niż nieprzyjazna agitacja',
            description: 'Kiedy traktujesz swoich konkurentów z uprzejmością i szacunkiem, jakich sam pragniesz, większość z nich odpowie w ten sam sopsób i w rezultaciepowstanie stabilny, wydajny i zyskowny interes. Z drugiej strony przemysł czy rynek, składający się z zawistnych, niemoralnych rywali, wkrótce zniszczy sam siebie. Kiedy ktoś pyta cię, jak twoje produkty i usługi wyglądają w porównaniu z konkurentami, mów o swych rywalach uprzejmie i z szacunkiem, ale wykorzystuj pytania, by skierować dyskusję na własną firmę i produkty. Przyznaj innym dobre strony, a potem przystąp do działania. Jeśli zbytnio utyskujesz na konkurencję, potencjalni klienci mogą się zastanawiać, co tracą i nie chcieć zawierać transakcji, dopóki nie porównają twoich produktów i usług z innymi.'
        }, {
            day: 6,
            motto: 'nikt nie może odnieść i utrzymać sukcesu bez przyjaznej współpracy z innymi',
            description: 'W dzisiejszym, powiązanym zależnościami społeczeństwie, w żadnym biznesie, zawodzie czy zajęciu praktycznie niemożliwe jest, by jednostka sięgała po szczyty sukcesu bez pomocy innych. Najlepszym sposobem syskania przyjaznej współpracy jest ofiarowanie jej. Kiedy masz w zwyczaju możliwie najczęstsze zachęcanie innych i pomaganie im w robieniu kariery, to większość z nich odwzajemni się, gdy sam będziesz potrzebował pomocy. Dawaj szczodrze, a na pewno przyniesie ci to pożytek.'
        }, {
            day: 7,
            motto: 'współpraca w zakładzie musi się rozpocząć od wierzchołka, jeśli ma się pojawić na dowolnych szczeblach - to samo dotyczy wydajności',
            description: 'W większości dużych instytucji ilość czasu i energii marnowanej na rywalizację pomiędzy oddziałami jest ogromna. Kierownicy rywalizujący z innymi wewnątrz firmy trwonią cenne zasoby, które powinny być skierowane ku spełnieniu misji firmy, jaką jest lepsze służenie klienteli. Co gorsze, negatywna, wewnętrzna koncentracja może powodować utratę sposobności, której pełny skutek ujawni się dopiero po miesiącach czy nawet latach. Niezależnie od tego, czy jesteś szefem oddziału, czy najmłodszym pracownikiem, możesz niezmiernie pomóc swojej firmie poprzez odmowę udziału w wewnętrznych walkach. Zamiast konkurować z innymi, rywalizuj sam ze sobą, aby wykonać pracę najlepiej jak potrafisz.'
        }, {
            day: 8,
            motto: 'przyjazna współpraca nie należy do dzieł szatana; on pracuje po przeciwnej stronie',
            description: 'Najbardziej szlacetne spośród ludzkich relacji zostały ukształtowane w duchu współpracy i harmonii. Współpraca na wiele sposobów jest fizycznym wyrazem twojej dbałości i troski o kolegów. Kiedy pracujesz z innymi w duchu przyjaznej współpracy, zachowujesz się zgodnie z podstawowymi zasadami większości religii i wszystkich udanych społeczeństw. Każdy czuje czasami targanie zazdrości i zawiści, któremu zwykle towarzyszy impuls do przysporzenia problemów lub kłopotów ludziom nielubianym. Prawdziwi jednak ludzie sukcesu nauczyli się powściągać takie odruchy. Wiedzą, że jeśli skoncentrują się na własnych celach i po drodze pomogą innym, to w końcu osiągną swoje zamierzenia. Nie jest łatwo zawsze być osobą przyjacielską i współpracującą, jednak w końcu przekonujemy się, że jest to warte wysiłku.'
        }, {
            day: 9,
            motto: 'przyjazna współpraca zawsze się opłaca, ponieważ tworzy wśród członków zespołu pozytywną postawę umysłową, która nie uznaje przeciwności',
            description: 'W każdym zorganizowanym przedsięwzięciu występują przeciwności. Czasem pojawiają się jako problemy techniczne; czasem są nieporozumieniem pomiędzy członkami zespołu co do szlaku, którym najlepiej pójść. Jeżeli dawałeś przykład inicjatywy i otwartego porozumiewania się, to okaże się, że twój zespół posiada zasoby umysłowe i duchowe, by przezwyciężyć tego typu walki.<br>Grupa ludzi, którzy wietzą swemu przywódcy i sobie nawzajem, nie będzie tracić energii, aby wygrać prestiż dla siebie. Wiedzą, że wszyscy skorzystają z rozwiązania i mają motywację, by znaleźć je, dzieląc się wiedzą i pomysłami. Z tych wielu elementów wprawny lider potrafi stworzyć konieczne rozwiązanie, jednak tylko wtedy, kiedy zwycięży duch przyjaźni i uczciwości.'
        }, {
            day: 10,
            motto: 'ci, którzy nie potrafią przyjmować z wdzięcznością poleceń, nie mają po co ich wydawać',
            description: 'Jeżeli jesteś lekkomyślnym czy kłótliwym pracownikiem, który nie potrafi przyjmować poleceń od innych, to twoim przeznaczeniem jest pozostanie na samym dole sił wytwórczych. Zanim będziesz mógł liczyć na przewodzenie innym ludziom, musisz nauczyć się skutecznie kierować samym sobą i swymi związkami z ludźmi, szczególnietymi na wyższych stanowiskach w firmie. Dopóki nie posiądziesz sztuki opanowywania swych relacji z własnym szefem czy szefami, nigdy nie będziesz w stanie zarządzać związkami z podwładnymi.'
        }, {
            day: 11,
            motto: 'pamiętaj, że nikt nie może zranić twoich uczuć bez twojej współpracy i przyzwolenia',
            description: 'Nikt nie może wywołać w tobie żadnej reakcji emocjonalnej, jeśli najpierw nie dasz mu na to pozwolenia. Tylko ty jesteś odpowiedzialny za swoje uczucie i emocje. Kiedy wiesz, co zamierzasz zrobić ze swoim życiem, nie pozwolisz, by męczące sytuacje na długo odciągnęły cię od twego celu. Jeśli wyznaczasz sobie ambitne cele i entuzjastycznie pracujesz dla niech, szybko zrozumiesz, że szkoda czasu na to, by pozwolić drobnym przykrościom przygnębiać cię i odwodzić od celu.'
        }, {
            day: 12,
            motto: 'jeśli odwiedzasz przyjaciół tylko wtedy, kiedy od nich czegoś potrzebujesz, wkrótce znajdziesz się bez przyjaciół',
            description: 'Jest wiele mądrości w starym powiedzeniu: "Jeśli pragniesz przyjaciół, bądź przyjacielem". Przyjaźć oznacza dawanie bez spodziewania się czegokolwiek w zamian. Zajęci ludzie sukcesu nie poszukują nowych znajomych. Jeśli chcesz stać się ich przyjacielem, musisz podjąć wysiłek, by się z nimi zaprzyjaźnić. Pozwól im poznać, że interesują cię jako ludzie, że nie zajmuje cię, co mogą dla ciebie zrobić, a może się okazać, iż zyskałeś prawdziwych i oddanych przyjaciół.'
        }, {
            day: 13,
            motto: 'do przyjaźni trzeba dorastać, a nie traktować jej za oczywistość',
            description: 'Twoi przyjaciele będą tym, kim ich uczynisz. Jeśli chętnie ofiarowujesz swój czas i zawsze okazujesz wrażliwość na innych, to twoi przyjaciele staną się uprzejmi i wspaniałomyślni. Jeżeli jesteś osobą, która przyjmuje istnienie przyjaciół za oczywistość, niewiele dając i nie oczekując w zamian, będziesz przyciągał przyjaciół przejawiających te same cechy. W przyjaźni podobieństwa się przyciągają.<br>Od czasu do czasu oceniaj swoje zachowanie, aby określić, do jakiego typu przyjaciół się zaliczasz. Czy przypominasz osobę, którą sam chciałbyś mieć za przyjaciela? Czy chętnie dajesz więcej niż spodziewasz się w zamian, czy też wciąż prosisz, a nigdy nie obdarowujesz? czy poświęcasz czas na to, by utrzymywać kontakt i pamiętać o różnych specjalnych okazjach przyjaciela? Kiedy zaczynasz być tak pochłonięty własnymi interesami, że zaopminasz o przyjaciołach, jesteś na najlepszej drodze pozostania bez przyjaciół.'
        }, {
            day: 14,
            motto: 'Jeżeli pragniesz znajomości bądź bogaty; jeśli zależy ci na przyjaźni, bądź przyjacielem',
            description: 'Nic tak jak pieniądze nie czyni cię atrakcyjnym i pociągającym dla innych. Jednak ludzie, których przyciągado ciebie tylko to, co możesz dla nich zrobić, stają się znajomymi, nie przyjaciółmi. Jeżeli zdobędziesz bogactwo, zyskasz wielu znajomych, ale nigdy nie będziesz miał prawdziwych przyjaciół, jeśli sam nei jesteś dla innych przyjacielem. Bądź bardzo ostrożny i selektywny w dobieraniu przyjaciół. Decyduj, by otaczać się pozytywnymi ludźmi, którzy lubią cię takiego, jakim jesteś i zachęcają, byś był sobą, i to najlpeszym jak potrafisz.'
        }, {
            day: 15,
            motto: 'jeśli musisz kogoś zawieść, upewnij się, czy nie jest to czasem przyjaciel, który podźignął cię, gdy byłeś na dnie',
            description: 'Wszyscy mamy krótką pamięć. Zajmujemy się zbytnio własnymi sprawami i codziennymi troskami, tracąc z oczu szlak przyjaciół. Z pewnością jednak nadejdzie chwila, kiedy będziesz musiał wybrać pomiędzy robieniem tego, czego pragniesz i tego, co musisz zrobić. Kiedy staniesz przed takimi decyzjami, pamiętaj, by nigdy, w żadnych okolicznościach nie porzucić prawdziwych i lojalnych przyjaciół, którzy byli przy tobie wówczas, kiedy ich potrzebowałeś.<br>Sprawiając zawód przyjacielowi, który pomógł ci w potrzebie, nie tylko ujemnie wpływasz na waszą przyjaźć, ale wyrządzasz też poważną szkodę szacunkowi dla samego siebie. Gdy rozczarowujesz przyjaciela, niezależnie od tego, jak ciężkie mogą być twoje własne obciążenia, sprzeniewierzasz się także samemu sobie. Jeżeli w żaden sposób nie możesz spełnić tego, czego chciałby twój dobry przyjaciel, znajdź inny sposób by mu to zrekompensować.'
        }, {
            day: 16,
            motto: 'przyjaciel to ktoś kto wie o tobie wszystko i nadal cię szanuje',
            description: 'Prawdziwy przyjaciel jest bezcennym darem. Jeśli odkrywamy swoje nadzieje, marzenia i najgłębsze tajemnice innym, a oni nadal nas lubią i szanują, to takich ludzi powinniśmy chołubić, pielęgnować. Zbyt często jedyną przyczynę, dla krótej inni pragną spędzać z nami czas - być naszymi przyjaciółmi - stanowi to, co sądzą, że możemy dla nich zrobić, a nie odwrotnie. Tymczasem prawdziwa przyjaźń jest wzajemna i każdy z przyjaciół korzysta tak samo.<br>Możesz zaskarbić sobie przyjaźń innych będąc osobą zasługującą na szacunek. Kiedy inni cię poważają, powinno to uczynić cię jeszcze bardziej świadomym twojej odpowiedzialności za traktowanie ich z takim samym szacunkiem i poważaniem.'
        }, {
            day: 17,
            motto: 'przyjaźń potrzebuje często wyrażania, aby utrzymać się przy życiu',
            description: 'wszyscy jesteśmy ludźmi, ze swymi chwilami słabości, słabostkami i niepewnościami. Każdy z nas potrzebuje, by być zauważonym z powodu czegoś wyjątkowego, co czyni nas niezwykłymi i pragniemy słyszeć, że się nas docenia. Utrzymywanie przyjaźni wymaga wysiłku i wytrwałego wyrażania, zarówno w słowach, jak i w czynach. Często mów swym przyjaciołom, jak bardzo ich cenisz. Pamiętaj o ważnych dla nich datach i okazjach. Gratuluj im osiągnięć. A najważniejsze, pozwól im poznać, że znajdujesz się przy nich zawsze, kiedy tylko cię potrzebują.'
        }, {
            day: 18,
            motto: 'przyjaźń widzi błędy u przyjaciela, ale o nich nie mówi',
            description: 'Prawdziwa przyjaźń rozpoznaje niedoskonałości, przyjmuje je jako część indywidualnej konstrukcji i skupia się na pozytywnych aspektach, zamiast tłumaczyć błędy. Przyjaciele nie chcą, byś komentował ich upadki, bardziej niż ty pragniesz krytyki z ich strony. Kiedy są zniechęcenie lub rozczarowani samymi sobą, słowa zachęty posłużą znacznie lepiej niż kazanie<br>Aby być przyjacielem, jakiego sam chciałbyś mieć, stań się dobrym słuchaczem, oferuj radę, kiedy cię o to proszą i ceń jak skarb zaufaie, jakie pokładają w tobie przyjaciele. Chwal ich za osiągnięcia i solidaryzuj się, kiedy im się nie udaje, ale unikaj oferowania "konstruktywnej krytyki" czy grania roli "adwokata diabła". Większość z nas wymaga od siebie znacznie więcej niż ktokolwiek inny i jesteśmy boleśnie świadomi naszych niedoskonałości. Przyjaciele nie muszą nam o nich przypominać.'
        }, {
            day: 19,
            motto: 'dobra drużyna piłkarska polega bardziej na harmonijnej współpracy niż na indywidualnych umiejętnościach',
            description: 'praca zespołowa jest "wysiłkiem współpracy członków zespołu w osiąganiu wspólnego celu". Kluczowe słowo w tej definicji stanowi wysiłek współpracy. Bez wsparcia całej grupy żadna drużyna nie przetrwa długo. Piłkarze dobrze wiedzą, że żaden z zawodników drużyny nie może być gwiazdą we wszystkich meczach. Większość chwil chwały opiera się na długiej serii gier, w których każdy jest wygrany dzięki oddanemu, zdeterminowanemu, angażującemu do szpiku kości blokowaniu i przytrzymywaniu przeciwnika.<br>Drużyna zwycięska to ta, która uznaje sukces jednego z członków zespołu za sukces całej drużyny. I odwrotnie, pewnym sposobem na wypracowanie przegranej jest tworzenie środowiska, w którym członkowie zespołu rywalizują ze sobą nawzajem zamiast z przeciwnikie. Kiedy wszyscy gracze dają z siebie wszystko w każdej sytuacji - czy prowadząc piłkę, czy robiąc miejsce dla kogoś innego - drużyna wygrywa i tak samo zwycięża każdy pojedynczy jej członek.'
        }, {
            day: 20,
            motto: 'gdy prosisz kogoś, by coś zrobił, powiedz mu: co, dlaczego, kiedy, gdzie i jak najlepiej może to uczynić',
            description: 'Na wszystkich ma wpływ własna przeszłość i doświadczenie. Postrzegamy polecenia w kontekście swego wykształcenia, doświadczenia, dziedzictwa, kultury własnej firmy i wielu innych czynników. Dobrzy kierownicy wiedzą o tym i starają się, by ich polecenia były jasne, zwęzłe i dobrze zrozumiane. Zdają sobie sprawę także z tego, że muszą opruszać się po wąskiej ścieżce pomiędzy wydaniem odpowiedniej instrukcji, a zabiciem motywacji pracowników przez pozbawienie ich wystarczającej swobody w wykonywaniu pracy.<br>Możesz uchwycić odpowiednią równowagę pomiędzy instruowaniem a motywacją poprzez zachęcenie pracowników do uczestniczenia w wyznaczaniu celów dla samych siebie i swojego zespołu, poprzez pomaganie im w opracowaniu planu osiągania ich celów oraz dopilnowanie, by każdy dokładnie rozuimał misję zespołu i swoją rolę w jej wypełnieniu. Zaproponuj, by członkowie zespołu zgłaszali się od czasu do czasu w celu powiadomienia o swych postępach, a potem zejdź im z drogi i tylko dopinguj do zwycięstwa.'
        }, {
            day: 21,
            motto: 'pamiętaj, że ton twego głosu często lepiej niż słowa oddaje to, co kryje się w twym umyśle',
            description: 'w chwili konfliktu propozycja czy kompromis optrafią ocalić zagrożoną relację w pracy. Zniechęcony pracownik może zostać ponownie zmotywowany za pomocą kilku starannie dobranych słów. W podobnych sytuacjach dobry kierownik patrzy poza bieżącą sytuację i działa w kierunku zachowania przyszłych korzyści. Jeżeli jednak twój głos zdradza gniew, strach czy rozpacz, to ta właśnie emocja, a nie mądrość, którą oferujesz, zostanie zapamiętana przez innych.<br>Ci, którzy wznieśli się na szczyt w dowolnej strukturze, potrafią kontrolować swoje emocje. Kiedy zajmujesz pozycję przywódczą, inni będą uważnie obserwować, jakie wysyłasz sygnały. Jeśli chcesz inspirować innych i okazywać, że dbasz o wszystkich członków swego zespołu, musisz nauczyć się kierować sobą i sposobami, jakimi przekazujesz wiadomości innym.'
        }, {
            day: 22,
            motto: 'we wszystkim we wszechświecie istnieje harmonia, za wyjątkiem relacji międzyludzkich',
            description: 'Nasz wszechświat charakteryzuje porządek i harmonia, jednak my jako istoty ludzki musimy wciąż walczyć, aby w naszych związkach osiągnąć takie same charakteerystyki. Właściwie istoty ludzkie zdają się uważać współpracę z innymi za nienaturalną. Jednostki odnoszące sukcec to ci, którzy nauczyli się płynąć pod prąd, robić to, czego inni nie chcą wykonywać. Posiedli sztukę wspólnej pracy dla korzyści całej grupy.<br>Osiągnięcie harmonii w jakimkolwiek związku - biznesowym, zawodowym czy osobistym - wymaga pracy. Znajdź pocieszenie w fakcie, że możesz zdobyć znacznie więcej pracując z innymi niż przeciw nim.'
        }, {
            day: 23,
            motto: 'tarcie w maszynach kosztuje; Tarcie w stosunkach międzyludzkich zubaża zarówno ducha, jak i konto bankowe',
            description: 'Niezgoda w dowolnej relacji ma często nieprzyjemne implikacje finansowe, ale najkosztowniejsza jest ona w wymiarze ludzkim. Kiedy jesteś uwikłany w pełen niezgody związek, energia fizyczna i umysłowa, która mogłaby być skierowana w stronę pozytywnych osiągnięś, zostaje niepotrzebnie rozproszona, roztrwoniona na stresujące, nnieproduktywne działania. Niestety, niezależnie od przyczyn tarcia pomiędzy ludźmi, zawsze ma ono zły wpływ na każdą z zaangażowanych osób.<br>Kiedy znajdujesz się w skłóconym związku, niewiele istnieje dopuszczalnych alternatyw. Możessz rozpracować swoje problemy albo opuścić zespół. Tylko ty wiesz, które z rozwiązań jest najlepsze dla ciebie, jednak jeśli obiektywnie ocenisz powody swojego zaangażowania w zespole i uznasz, że wciąż są aktualne, to najlepszy trybem postępowania może być przeniknięcie dupy i znalezienie rozwiązania dającego się zaakceptować przez wszystkich. Jeżeli nie możesz tego zrobić, to chyba nadszedł czas na opuszczenie partnerów i poszukani innej drogi w kierunku twojego celu.'
        }, {
            day: 24,
            motto: 'jeśli nie potrafisz zgodzić się z innymi, możesz przynajmniej powstrzymać się od kłótni z nimi',
            description: 'Kiedy zaplączesz się w kłótnię z drugą osobą, to może to być jedyna sytuacja, w której nierobienie niczego jest lepsze od robienia czegoś. Oto praktyczna przyczyna takiego stanu rzeczy: kiedy kłócisz się z innymi - nawet jeśli wygrasz spór - obciążasz się dużym ciężarem niepotrzebnego stresu. Nie możesz zachowywać pozytywnej postawy umysłowej, kiedy pozwalasz negatywnym emocjom, takim jak złość czy nienawiść, zdominować twe myśli.<br>Nikt nie może cię przynębić ani rozzłościć, jeśli nie pozwolisz mu na to. Zamiast kłócić się z innymi, spróbuj zadawać nie zagrażające nikomu pytania, takie jak - dlaczego czujes się w ten sposób? czym cię rozzłościłem? co mogę zrobić, by ci pomóc? Może się okazać, że cała sytuacja powstała w wyniku niporozumienia, które szybko da się naprawić. Nawet jeśli problemy są poważniejsze, twoje pozytywne zachowanie w dużej mierze przyczyni się do ich rozwiązania.'
        }, {
            day: 25,
            motto: 'pamiętaj, że do prowadzenia kłótni potrzeba co najmniej dwojga ludzi',
            description: 'W ogniu niezgody trudno jest pamiętać, że do kłótni potrzeba dwóch osób. Pomocne może się okazać przypomnienie sobie, że nikt nie może się z tobą nie zgadzać, żeśli ty zgadzasz się z nim. Nie próbujemy sugerować, że powinieneś iść na kompromis co do swoich norm. Można jednak pozostać wiernym swoim pzekonaniom, jednocześnie poszukując płaszczyzny produktywnej współpracy z tymi, którzy na początku nie zgadzali się z sobą.<br>Jeśli ktoś jest wytrącony z równowagi z twego powodu lub z powodu sytuacji, która dotyczy ciebie, daj mu poznać, że rozumiesz, jak się czuje. Przebadaj problem z jego punktu wydzenia. Co jest źródłem konfliktu? W jaki sposób mógłby być rozwiązany dla dobra interesów wszystkich zaangażowanych? Jaki był twój udział w powstaniu problemu? Kiedy starasz się znaleźć rozwiązanie, zamiast usiłować zrzucić na kogoś winę, inni prawie zawsze zareagują w podobny sposób.'
        }, {
            day: 26,
            motto: 'wzajemne zrozumienie stanowi fundament wszystkich zadowalających związków międzyludzkich',
            description: 'Kiedy nawiązujemy relację, większość z nas stawia dwa podstawowe pytania: "czy mogę ci ufać?" i "Czy na prawdę dbasz o mnie?" Zależnie od naszych wcześniejszych sukcesów w partnerstwie z innymi - osobistym czy w buznesie - odpowiedź może nie nadejść szybko. Zaufanie do drugiego człowieka często rozwija się stopniowo, w miarę jak osoby zaangażowane w związek oddają się sukcesowi i szczęściu drugiego.<br>Chociaż zaufanie i zawierzenie stanowią podstawowe podpory wszystkich udanych związków, to jednak są kruche i delikatne. Relacja trwająca miesiące czy nawet lata może zostać nieodwracalnie zniszczona przez kilka niegrzecznych słów czy pojedynczy, bezmyślny czyn. Nie pozwól sobie na działanie w pośpiechu albo utratę kontroli nad emocjami w ważnych dla ciebie związkach.'
        }, {
            day: 27,
            motto: 'dobry rybak, robi wszystko, by założyć jako przynętę to, co lubi ryba - może się to okazać dobrą radą dla tych, którzy pragną powodzenia w relacjach międzyludzkich',
            description: 'Podobnie jak w rozmowie dobrze jest raczej słuchać niż mówić, tak w relacjach międzyludzkich mądrze jest mieć na względzie bardziej dobro innych niż własne życzenia i pragnienia. Jeśli stale usiłujesz traktować innych tak, jakbyś chciał, by oni traktowali ciebie, stajesz się osobą, którą inni lubią mieć w pobliżu, tym kto budzi ich szacunek, zaufanie i lojalność.<br>Kiedy nauczysz się kierować swoimi emocjami i własnym ja oraz zważać zawsze na potrzeby i pragnienia innych, to w nieunikniony sposób "założysz na swój haczyk przynętę" uprzejmości i wrażliwości oraz "złapiesz" więcej przyjaciół niż mógłbyś zliczyć.'
        }, {
            day: 28,
            motto: 'tym, którzy tworzą dobre koleżeństwo, nigdy nie zabraknie przyjaciół',
            description: 'Jeśli masz przyjaciela, który zbacza ze swej drogi, by umocnić przyjaźń pomiędzy wami, uważaj się za wyjątkowego szczęściarza. W dzisiejszych szalonych, ruchliwych społeczeństwach takie jednostki zdarzają się niezmiernie rzadko. Przy wymaganiach narzucanych przez kariery, rodziny i wściekłe tempo codziennego życia, większość z nas ma mało czasu dla siebie, a jeszcze mniej dla przyjaciół. A przecież wiemy, że ofiarowana darmo i z wdzięcznością przyjęta przyjaźń jest jednym z najwspanialszych darów życia.'
        }, {
            day: 29,
            motto: 'każdy trwały sukces jest oparty o harmonijne relacje międzyludzkie',
            description: 'Większość z nas nie potrafi "przejść tego w pojedynkę". Wszyscy potrzebujemy innych - czy to w naszych karierach, relacjach osobistych czy w życiu - jeśli mamy osiągnąć poziom sukcesu, jakiego pragniemy. Poza tym, jaki byłby sens posiadania tego wszystkeigo, gdybyśmy nie mieli nikogo, na kim nam zależy, by z nim to dzielić? Możesz sam zdecydować, czy pracować z innymi, czy ignorować ich czy też działać przeciw nim, jednak największe sukcesy w życiu przychodzą do tych, którzy harmonijnie pracują z innymi. Kiedy twoje osobiste cele są zbieżne z celami innych, to nie tylko siła wspólnej pracy przynosi wam korzyście, ale też taka współpraca powoduje występowanie efektu synergicznego*, który pozwala zdobyć znacznie więcej ponad zwykłą sumę indywidualnych wysiłków.<br><br>*Efekt synergiczny - współdziałanie różnych czynników, skuteczniejsze niż suma ich oddzielnych działań'
        }, {
            day: 30,
            motto: 'jeśli musisz wkraczać w stosunki międzyludzkie, postaraj się wprowadzać pokój; przekonasz się, że nie będziesz miał dużej konkurencji',
            description: 'Kiedy stajemy wobec konfliktu pomiędzy osobami, większość z nas skłania się raczej ku odsunięciu się od sytuacji niż zaangażowaniu w nią. Jeśli pozwalamy sobie na włączenie się, zwykle przyjmujemy stanowisko jednej ze stron kosztem drugiej. Oczywiście, takie zachowanie niewiele przyczynia się do rozwiązania problemu i może w rzeczywistości rozjątrzyć sprawę. Jednak kiedy podejmujesz prawdziwą próbę rozwiązania sytuacji, nie powinieneś się dziwić, jeśli okażesz się jedyny.<br>Wszyscy jesteśmy jednostkami skomplikowanymi, o uczuciach i emocjach, które nie zawsze w pełni rozumiemy. Czasem samo zaangażowanie się strony nie zainteresowanej wystarczy, by pomóc w rozwiązaniu sporu. Jeśli jednak znajdziesz się pośrodku, upewnij się, że nie pozwalasz sobie wejść na pozycję, w której musisz wybierać pomiędzy pragnieniami tych osób. Pracuj nad kompromisem najlepiej służącym interesom każdego.'
        }, {
            day: 31,
            motto: 'kiedy dwoje lub więcej ludzi łączy swoje myśli i działania w duchu harmonii dla osiągnięcia określinego celu, to mają zapewnioną niemal nieograniczoną moc',
            description: 'Mistrzowski związek umysłów obejmuje dwie lub więcej osób wspólnie pracujących w idealnej harmonii nad osiągnięciem jednego celu. Takie partnerstwo stwarza super siłę, która umożliwia każdemu z członków robienie więcej, niż którykolwiek byłby w stanie dokonać w pojedynkę. Starannie dobieraj partnerów do takiej współpracy. Łącz się z ludźmi, których zalety uzupełniają twoje. Jeżeli na przykład jesteś osobą bardzo kreatywną, trzyskającą genialnymi pomysłami, to idealnym zrównoważeniem twoich skłonności twórczych będzie osoba logiczna, o uporządkowanym, analitycznym umyśle. Przede wszstkim jednak otaczaj się ludźmi, którzy podzielają twoje pozytywne wartości i oddanie podobnym poziomom dokonań.'
        }]
    }, {
        name: 'sierpień',
        motto: 'klęska i porażka',
        days: [{
            day: 1,
            motto: 'edison zawiódł dziesięć tysięcy razy zanim udoskonalił żarówkę elektryczną - nie martw się, jeśli raz ci się nie powiedzie',
            description: 'Bezsprzecznie największy wynalazca Ameryki, Thomas Edison, posiadał wyjątkowo pozytywne postrzeganie świata, które znacznie zwiększało jego zdolności jako wynalazcy. Podczas gdy inni mogliby popaść w beznadziejne zniechęcenie po tysiącu nieudanych prób nad uzyskaniem światła elektrycznego, wielki Edison traktował każdy niepomyślny eksperyment jako eliminację projektu, który się nie sprawdziła, a więc zbliżający go do udanego rozwiązania<br>Wszyscy możemy się uczyć od Edisona. Historia obfituje w opowieści o wynalazcach, którzy zbyt wcześnie zrezygnowali i poddali, się czy górnikach, którzy znaleźli złoto dostłownie metr od miejsca, gdzie ktoś inny przestał kopać. Niewiele jest w życiu przeszkód, które nie ustąpią konsekwentnemu, wytrwałemu, inteligentnemu i pozytywnemu działaniu. Kiedy zniechęcasz się po niepowodzeniu, przypomnij sobie dziesięć tysięcy poreażek poniesionych przez Edisona, zanim doszedł do rozwiązania, które na zawsze zmieniło świat.'
        }, {
            day: 2,
            motto: 'przeciętny człowiek zrezygnowałby przy pierwszej porażce - dlatego jest tylu przeciętnych ludzi, a tylko jeden Edison',
            description: 'Edison zauważył kiedyś, że większość ludzi nie rozpoznaje okazji, kiedy ta puka, ponieważ często pojawia się ona w przebraniu i wygląda jak praca. Wiedział, że nic wartościowego nigdy nie przychodzi łatwo; gdyby było proste, każdy mógłby to zrobić. Ponieważ jego wytrwałość znacznie wykraczała poza to, co przeciętny człowiek uznawałby za tozsądne i racjonalne, dokonał wynalazków, które nawet najbardziej wykształcone jednostki jego czasów uznawały za niemożliwe.<br>Wielkie postępy w nauce są często dokonywane przez ludzi o niemal fanatycznym oddaniu poszukiwanium rozwiązania jakiegoś problemu. Same przebłyski inspiracji nie wystarczą, by zapewnić sukces. Musi po nich nastąpić zdeterminowanie, wytrwałe działanie.'
        }, {
            day: 3,
            motto: 'dryfowanie bez celu i sensu jest największą porażką',
            description: 'Nie mając planu dla własnego życia, łatwo wybrać drogę najmniejszego oporu, poddać się przepływowi, i dryfować z prądem bez konkretnego celu w umyśle. Posiadanie wyraźnego plany swego życia znacznie upraszcza podejmowanie setek codziennych decyzji, które wpływają na ostateczny sukces. Kiedy wiesz, dokąd zmierzasz, łatwoci zdecydować, czy twoje działania kierują się w stronę twego celu czy w przeciwną. Bez dokładnych, precyzyjnych celów i planu ich zdobycia każda decyzja jest zawieszona i podejmowana w próżni. Wyrazistość celu zapewnia kontekst i pozwala odnosić poszczególne czyny do całościowego planu.'
        }, {
            day: 4,
            motto: 'ułatwianie życia dzieciom często utrudnia je im w dorosłości',
            description: 'Del Smith, milioner, założyciel i prezes Evergreen International Aviation mówił często: "całe szczęście, że urodziłem się biedakiem - nauczyłem się pracować". Pidobnie jak wielu innych, którzy o własnych siłach dotarli na sam szczyt, Smith uważa, że największym darem, jaki można dać dziecku, jest nauczenie go wartości pracy. Dar ten nigdy nie może zostać zgubiony ani ukradziony. Donaturalnych pragnień rodziców należy chęć zapewnienia dzieciom tych dóbr materialnyck, jakich sami nie mieli w dzieciństwie. Jednak taka szczodrość często pozbawia dzieci największego daru, jaki im można ofiarować: zdolności zadbania o siebie. Kiedy czynisz życie dzieci "trudnym" poprzez wymaganie od nich nauczenia się wartości pracy, zyskują znacznie większe prawdopodobieństwo sukcesu w dorosłym życiu.'
        }, {
            day: 5,
            motto: 'większość z nas nie ma za złe mówienia o naszych błędach, jeśli krytyka jest na tyle łaskawa, by wspomnieć również o zaletach',
            description: 'Obrona siebie i swego zachowania jest normalną reakcją w momencie, kiedy ktoś nas krytykuje - nawet w głębi przynajemy, że to, co się nam mówi, jest prawdą. Ci jednak, którzy osiągają w życiu wielki sukces, nauczyli się odkładać na bok swe emocje i uczyć się od innych, mimo że przesłanie może być nieprzyjemne.<br>Kiedy ktoś inny cię ocenia, pamiętaj, iż krytyka jakiegoś aspektu twojego postępowania nie stanowi ataku osobistego na ciebie. Kontroluje swoje reakcje emocjonalne i przyswajaj pożyteczne koncepcje, nawet gdyby ci się nie podobał sposób, w jaki informacja jest przekazywana.'
        }, {
            day: 6,
            motto: 'sukces nie wymaga wyjaśniej - porażka musi być leczona wymówkami',
            description: 'Najpewniejszym sposobem zdobycia akceptacji w dowolnej instytucji czy rodzaju pracy jest odnoszenie sukcesu. Niestey, w życiu tak się nie dzieje. Bez względu na to, jak starannie przyswajasz sobie temat, jak racjonalnie podejmuejsz decyzje, jak dobrze jesteś przygotowany, będziesz czasem popełniał błędy. Istoty ludzkie po prostu są omylne. Ważne jest jednak zrozumienie tego, że chwilowe nipowodzenia nie oznaczają permanentnej klęski.<br>Ludzie sukcesu przyznają, iż wszyscy doświadczamy okresowych zahamowań, wymagających od nas przewartościowania działań i podjęcia kroków korekcyjnych w celu ponownego sięgania po sukces. Wiedzą oni, że przeciwność nigdy nie trwa wiecznie.'
        }, {
            day: 7,
            motto: 'istnieje ogromna różnica pomiędzy klęską a chwilową porażką',
            description: 'Nie istnieje coś takiego jak klęska, dopóki nie zostanie za taką przyjęta. Każda porażka jest chwilowa, chyba że się poddasz i pozwolisz jej stać się trwałą. W rzeczywistości często zdarza się, że okresowe niepowodzenie czyni nas silniejszymi i bardziej zdolnymi. Za każdym razem kiedy próbujemy i zawodzimy, uczymy się czegoś, co pomaga nam przygotować się do ostatecznego sukcesu.<br>Tylko podczas lekcji w szkole na każede ppytanie istnieje prawidłowa odpowiedź. Jeśli stosujesz jakieś podejście, które się nie sprawdza, spróbuj czegoś innego. Jeżeli traktujesz przeciwność wyłącznie jako doświadczenie, które uczy, to ilość twoich sukcesów znacznie przewyższy liczbę porażek.'
        }, {
            day: 8,
            motto: 'Twoja prawdziwa odwaga ukazuje się najlepiej w godzinie przeciwności',
            description: 'Niektóre niepowodzenia są tak poważne, że poddanie się im oznacza przegranie całej gry. Kiedy generam Matthew Ridgway* przejmował dowództwo w wojnie koreańskiej, jego siły były zepchnięte daleko na wschód, pod silnym naporem wroga, Tylko zdeterminowana decyzja utrzymania linii pozwoliła siłom amerykańskim obronić się przed zepchnięciem do morza, a potem odzyskać stracone nerytorium. <br>Kiedy uderza porażka, możesz nie mieć czasu na wycofanie się i przemyślenie błędów bez ryzyka niepowodzenia. Nie ulega paraliżowi. W takiej chwili ważne jest wiedzieć, czego naprawdę pragniesz i tak działać, aby uchronić swoje zasoby i nadzieje. Jeśli kompletnie się rozsypiesz, przyjmiesz sios w poczucie własnej wargości, który będzie trudny do naprawienia. W zamian przylgnij do swych zasad, a będziesz przynajmniej wiedział, że ochroniłeś, to co masz najcenniejszego.<br><br>*Matthew ridgway, w 1950 r. dowódca amerykańskiej 8 armii i wojsk lądowych ONZ w Korei, w 1951 r. głównodowodzący wojs ONZ w Korei i dowódca sił sprzymierzonych w Japonii;'
        }, {
            day: 9,
            motto: 'zawsze pozostaje sposobność, by rozpocząć od nowa',
            description: 'Nigdy nie możesz utracić dwóch ze swych najważniejszych aktywów, choć może się to zdawać nieprawdą przy pierwszym poważnym uderzeniu, jakiego doświadczysz. Aktywami tymi są moc twego umysłu i wolność jej wykorzystania. Gdy tylko zrozumiesz, co cię pognębiło, możesz rozpoczynać formowanie nowych planów. Możesz nie mieć pieniędzy, które kiedyś posiadałeś; może ci zabraknąć znajomości, jakie nawiązałeś. Wciąż jednak masz przywilej świadomości tego, że świat w końcu wynagradza uczciwy wysiłek oraz dysponujesz doświadczeniem pomyłek, których nigdy więcej nie popełnisz.<br>Pamiętaj, że niezależnie od tego, gdzie jesteś teraz, cokolwiek potrafisz wymyślić i w co uwierzyć, tego możesz dokonać.'
        }, {
            day: 10,
            motto: 'większość klęsk można by zamienić w sukces, gdyby ktoś wytrwał jeszcze jedną chwilę lub włożył więcej wysiłku',
            description: 'Kiedy nosisz w sobie potencjał sukcesu, przeszkody i chwilowe niepowodzenia pomagają ci tylko przygotować się do sięgnięcia prawdziwych wyżyn. Bez przeciwności, lojalności, pokory i wytrwałości, które są tak istotne w trwałym sukcesie. Wielu ludzi uniknęło szponów porażki i osiągnęło wielkie zwycięstwa, ponieważ nie pozwoliło sobie na zawód. Gdy wszystkie drogi ucieczki zostają odcięte, zaskoczy cię szybkość, z jaką odnajdziesz ścieżkę do sukcesu.'
        }, {
            day: 11,
            motto: 'zgodnie z prawem harmonijnego przyciągania sukces przyciąga sukces, a porażka przyciąga porażkę',
            description: 'W fizyce przyciągają się znaki przeciwne, jednak w relacjach międzyludzkich jest odwrotnie. Negatywni ludzie przyciągają tylko innych negatywnych ludzi, podczas gdy pozytywni myśliciele przyciągają jednostki o podobnych umysłach. Zauważysz, że kiedy zaczniesz osiągać sukces, nastąpią kolejne sukcesy. To prawo harmlnijnego przyciągania. Kiedy bogactwa pojawią się na twoojej drodze, zdziwi cię, jak szybkok się gromadzą.<br>wyćwicz swój umysł w wyobrażaniu sobie siebie zdobywającego określoną ilość bogactwa czy osiągającego pewien cel - czegokolwiek pragniesz najbardziej. Potem użyj autosugestii, by przekonać swą podświadomość, że możes ten cel osiągnąś i wprowadzić w czyn swój plan. Kiedy wykorzystasz narzędzia, jakimi dysponujeszs w przygotowaniu się do sukcesu i wyobrazisz sobie siebie już jako zdobywcę, możesz osiągnąć każdy rozsądny cel, jaki sobie wyznaczysz.'
        }, {
            day: 12,
            motto: 'ktoś, kto stara się zyskać coś za nic, zwykle kończy na osiągnięciu niczego za coś',
            description: 'Ci, którzy sądzą, że mogą przejść przez życie bez oddawania takiej samej wartości jak otrzymują, w końcu przekonują się, że pracują znacznie więcej, aby oszukać innych, a otrzymją bardzo niewiele w zamian. Życie ma dziwny sposób wyrównywania rachunków. W długiej perspektywie otrzymasz taką samą miarę, jaką dajesz. Poświęcaj czas na produktywne, pozytywne wysiłki, hojnie rozdzielaj swój czas i talenty, a wyróżniesz się z mnogości tych, którzych głównym celem w życiu zdaje się być otrzymanie czegoś za nic.'
        }, {
            day: 13,
            motto: 'ludzie uprawiający hazard dla pieniędzy są potencjalnymi oszustami, ponieważ próbują dostać coś za nic',
            description: 'Ktoś kto ryzykuje swoje bogactwo dla złudnego kaprysu losu, nie jest zazwyczaj osobą, jaką chciałbyś mieć za partnera w interesach. Istnieją jednostki szczególnie podatne na pokusę pójścia na skróty w dziedzinie jakości produktu, bezpieczeństwa pracy i w ogóle skłonne do niewypełniania swoich obietnic. Przez dłuższy czas jednak nie można dostawać czegoś za nic. Prawo kompensacji jest nieubłagane w swym wymaganiu, abyś otrzymywał to, na co zasłużysz. Czasem możesz czuć, że zasługujesz na więcej - i może tak być w istocie - jednak ostatecznie twoja zapłata będzie proporcjonalna do twoich wysiłków'
        }, {
            day: 14,
            motto: 'czy to nie dziwne, że niektórzy ludzie są tak sprytni w wymyślaniu wymówek, a tak tępi w wykonywaniu pracy, że alibi staje się bezużyteczne?',
            description: 'Gdyby ludzie wykonywali swą pracę z połową wysiłku i kreatywności, jaką poświęcają na próżne usiłowanie oszukania innych, mogliby we wszystkim osiągnąć wielki sukces. Czasami kusi, by naśladować tych, którzy zdają się przemykać bez specjalnej pracy, jednak ci, którzy oszukują swoją firmę, nie robiąc tego, za co im się płaci, w końcu zapłacą za to cenę. Zapłacą utratą swej najcenniejszej wartości: własnej reputacji. Wartość opinii uczciwości i rzetelności stanowi o różnicy pomiędzy karierą wypełnioną obietnicami a życiem klęzki.'
        }, {
            day: 15,
            motto: 'cudze błędy są kiepską wymówką dla twoich własnych',
            description: 'Ralph Waldo Emerson powiedział: "Łatwo jest żyć na świecie zgodnie z opinią świata; łatwo w samotności żyć wwedłyg własnej; ale wielkim człowiekiem jest ten, kto z doskonałym wdziękiem zachowuje niezależność samotności pośrodku tłumu". Będąc częścią grupy, łatwo jest pójść z prąde, by przebić się. Kiedy jednak jesteś w stanie utrzymywać własne, najwyższe normy uczciwości - niezależnie od tego, co mogą robić inni - wtedy jesteś przeznaczony do wielkości.<br>Skoro opracujesz własny, dokładnie przemyślany kodeks osobistego prowadzenia się, wówczas nigdy nie będziesz musiał pytać nikogo, jaki powinien być właściwy przebieg działania. Będziesz to wiedział intuicyjnie.'
        }, {
            day: 16,
            motto: '',
            description: ''
        }, {
            day: 17,
            motto: '',
            description: ''
        }, {
            day: 18,
            motto: '',
            description: ''
        }, {
            day: 19,
            motto: '',
            description: ''
        }, {
            day: 20,
            motto: '',
            description: ''
        }, {
            day: 21,
            motto: '',
            description: ''
        }, {
            day: 22,
            motto: '',
            description: ''
        }, {
            day: 23,
            motto: '',
            description: ''
        }, {
            day: 24,
            motto: '',
            description: ''
        }, {
            day: 25,
            motto: '',
            description: ''
        }, {
            day: 26,
            motto: '',
            description: ''
        }, {
            day: 27,
            motto: '',
            description: ''
        }, {
            day: 28,
            motto: '',
            description: ''
        }, {
            day: 29,
            motto: '',
            description: ''
        }, {
            day: 30,
            motto: '',
            description: ''
        }, {
            day: 31,
            motto: '',
            description: ''
        }]
    }, {
        name: 'wrzesień',
        motto: 'dodatkowy tysiąc kroków',
        days: [{
            day: 1,
            motto: '',
            description: ''
        }, {
            day: 2,
            motto: '',
            description: ''
        }, {
            day: 3,
            motto: '',
            description: ''
        }, {
            day: 4,
            motto: '',
            description: ''
        }, {
            day: 5,
            motto: '',
            description: ''
        }, {
            day: 6,
            motto: '',
            description: ''
        }, {
            day: 7,
            motto: '',
            description: ''
        }, {
            day: 8,
            motto: '',
            description: ''
        }, {
            day: 9,
            motto: '',
            description: ''
        }, {
            day: 10,
            motto: '',
            description: ''
        }, {
            day: 11,
            motto: '',
            description: ''
        }, {
            day: 12,
            motto: '',
            description: ''
        }, {
            day: 13,
            motto: '',
            description: ''
        }, {
            day: 14,
            motto: '',
            description: ''
        }, {
            day: 15,
            motto: '',
            description: ''
        }, {
            day: 16,
            motto: '',
            description: ''
        }, {
            day: 17,
            motto: '',
            description: ''
        }, {
            day: 18,
            motto: '',
            description: ''
        }, {
            day: 19,
            motto: '',
            description: ''
        }, {
            day: 20,
            motto: '',
            description: ''
        }, {
            day: 21,
            motto: '',
            description: ''
        }, {
            day: 22,
            motto: '',
            description: ''
        }, {
            day: 23,
            motto: '',
            description: ''
        }, {
            day: 24,
            motto: '',
            description: ''
        }, {
            day: 25,
            motto: '',
            description: ''
        }, {
            day: 26,
            motto: '',
            description: ''
        }, {
            day: 27,
            motto: '',
            description: ''
        }, {
            day: 28,
            motto: '',
            description: ''
        }, {
            day: 29,
            motto: '',
            description: ''
        }, {
            day: 30,
            motto: '',
            description: ''
        }, {
            day: 31,
            motto: '',
            description: ''
        }]
    }, {
        name: 'październik',
        motto: 'Twój umysł',
        days: [{
            day: 1,
            motto: '',
            description: ''
        }, {
            day: 2,
            motto: '',
            description: ''
        }, {
            day: 3,
            motto: '',
            description: ''
        }, {
            day: 4,
            motto: '',
            description: ''
        }, {
            day: 5,
            motto: '',
            description: ''
        }, {
            day: 6,
            motto: '',
            description: ''
        }, {
            day: 7,
            motto: '',
            description: ''
        }, {
            day: 8,
            motto: '',
            description: ''
        }, {
            day: 9,
            motto: '',
            description: ''
        }, {
            day: 10,
            motto: '',
            description: ''
        }, {
            day: 11,
            motto: '',
            description: ''
        }, {
            day: 12,
            motto: '',
            description: ''
        }, {
            day: 13,
            motto: '',
            description: ''
        }, {
            day: 14,
            motto: '',
            description: ''
        }, {
            day: 15,
            motto: '',
            description: ''
        }, {
            day: 16,
            motto: '',
            description: ''
        }, {
            day: 17,
            motto: '',
            description: ''
        }, {
            day: 18,
            motto: '',
            description: ''
        }, {
            day: 19,
            motto: '',
            description: ''
        }, {
            day: 20,
            motto: '',
            description: ''
        }, {
            day: 21,
            motto: '',
            description: ''
        }, {
            day: 22,
            motto: '',
            description: ''
        }, {
            day: 23,
            motto: '',
            description: ''
        }, {
            day: 24,
            motto: '',
            description: ''
        }, {
            day: 25,
            motto: '',
            description: ''
        }, {
            day: 26,
            motto: '',
            description: ''
        }, {
            day: 27,
            motto: '',
            description: ''
        }, {
            day: 28,
            motto: '',
            description: ''
        }, {
            day: 29,
            motto: '',
            description: ''
        }, {
            day: 30,
            motto: '',
            description: ''
        }, {
            day: 31,
            motto: '',
            description: ''
        }]
    }, {
        name: 'listopad',
        motto: 'zdrowie i szczęście',
        days: [{
            day: 1,
            motto: '',
            description: ''
        }, {
            day: 2,
            motto: '',
            description: ''
        }, {
            day: 3,
            motto: '',
            description: ''
        }, {
            day: 4,
            motto: '',
            description: ''
        }, {
            day: 5,
            motto: '',
            description: ''
        }, {
            day: 6,
            motto: '',
            description: ''
        }, {
            day: 7,
            motto: '',
            description: ''
        }, {
            day: 8,
            motto: '',
            description: ''
        }, {
            day: 9,
            motto: '',
            description: ''
        }, {
            day: 10,
            motto: '',
            description: ''
        }, {
            day: 11,
            motto: '',
            description: ''
        }, {
            day: 12,
            motto: '',
            description: ''
        }, {
            day: 13,
            motto: '',
            description: ''
        }, {
            day: 14,
            motto: '',
            description: ''
        }, {
            day: 15,
            motto: '',
            description: ''
        }, {
            day: 16,
            motto: '',
            description: ''
        }, {
            day: 17,
            motto: '',
            description: ''
        }, {
            day: 18,
            motto: '',
            description: ''
        }, {
            day: 19,
            motto: '',
            description: ''
        }, {
            day: 20,
            motto: '',
            description: ''
        }, {
            day: 21,
            motto: '',
            description: ''
        }, {
            day: 22,
            motto: '',
            description: ''
        }, {
            day: 23,
            motto: '',
            description: ''
        }, {
            day: 24,
            motto: '',
            description: ''
        }, {
            day: 25,
            motto: '',
            description: ''
        }, {
            day: 26,
            motto: '',
            description: ''
        }, {
            day: 27,
            motto: '',
            description: ''
        }, {
            day: 28,
            motto: '',
            description: ''
        }, {
            day: 29,
            motto: '',
            description: ''
        }, {
            day: 30,
            motto: '',
            description: ''
        }, {
            day: 31,
            motto: '',
            description: ''
        }]
    }, {
        name: 'grudzień',
        motto: 'wiara i nadzieja',
        days: [{
            day: 1,
            motto: '',
            description: ''
        }, {
            day: 2,
            motto: '',
            description: ''
        }, {
            day: 3,
            motto: '',
            description: ''
        }, {
            day: 4,
            motto: '',
            description: ''
        }, {
            day: 5,
            motto: '',
            description: ''
        }, {
            day: 6,
            motto: '',
            description: ''
        }, {
            day: 7,
            motto: '',
            description: ''
        }, {
            day: 8,
            motto: '',
            description: ''
        }, {
            day: 9,
            motto: '',
            description: ''
        }, {
            day: 10,
            motto: '',
            description: ''
        }, {
            day: 11,
            motto: '',
            description: ''
        }, {
            day: 12,
            motto: '',
            description: ''
        }, {
            day: 13,
            motto: '',
            description: ''
        }, {
            day: 14,
            motto: '',
            description: ''
        }, {
            day: 15,
            motto: '',
            description: ''
        }, {
            day: 16,
            motto: '',
            description: ''
        }, {
            day: 17,
            motto: '',
            description: ''
        }, {
            day: 18,
            motto: '',
            description: ''
        }, {
            day: 19,
            motto: '',
            description: ''
        }, {
            day: 20,
            motto: '',
            description: ''
        }, {
            day: 21,
            motto: '',
            description: ''
        }, {
            day: 22,
            motto: '',
            description: ''
        }, {
            day: 23,
            motto: '',
            description: ''
        }, {
            day: 24,
            motto: '',
            description: ''
        }, {
            day: 25,
            motto: '',
            description: ''
        }, {
            day: 26,
            motto: '',
            description: ''
        }, {
            day: 27,
            motto: '',
            description: ''
        }, {
            day: 28,
            motto: '',
            description: ''
        }, {
            day: 29,
            motto: '',
            description: ''
        }, {
            day: 30,
            motto: '',
            description: ''
        }, {
            day: 31,
            motto: '',
            description: ''
        }]
    }]
}
