let plan = {
    months: [{
        name: 'styczeń',
        motto: 'cechy charakteru',
        days: [{
            day: 1,
            motto: 'niezawodność jest fundamentem dobrego charakteru',
            description: 'Ludzie z charakterem robią to - co mówią, że zrobią, wtedy - kiedy mówią, że zrobią i zgodnie z ustalonymi warunkami. Są liderami, do których inni zwracają się o prowadzenie, ponieważ udowodnili, że zależy im i można im zaufać. Jeśli szanujesz siebie na tyle, by dotrzymywać zobowiązań nawet wtedy, gdy jest to dla ciebie niewygodne, inni również zaczną cię szanować.<br>Niezawodność, podobnie jak inne cechy charakteru, jest nawykiem. Zacznij dzisiaj - na początku nowego roku - kształtować postawę niezawodności. Jeśli odkładasz sprawy lub trudno ci dotrzymywać przyrzeczeń, rozpocznij od rzeczy drobnych. Obiecaj sobie, że na przykład będziesz punktualny i tak zorganizuj czas, by dotrzymać najbliższego terminu. wkrótce przekonasz się, że łatwiej ci będzie wypełniać inne zobowiązania.'
        }, {
            day: 2,
            motto: '',
            description: ''
        }, {
            day: 3,
            motto: '',
            description: ''
        }, {
            day: 4,
            motto: '',
            description: ''
        }, {
            day: 5,
            motto: '',
            description: ''
        }, {
            day: 6,
            motto: '',
            description: ''
        }, {
            day: 7,
            motto: '',
            description: ''
        }, {
            day: 8,
            motto: '',
            description: ''
        }, {
            day: 9,
            motto: '',
            description: ''
        }, {
            day: 10,
            motto: '',
            description: ''
        }, {
            day: 11,
            motto: '',
            description: ''
        }, {
            day: 12,
            motto: '',
            description: ''
        }, {
            day: 13,
            motto: '',
            description: ''
        }, {
            day: 14,
            motto: '',
            description: ''
        }, {
            day: 15,
            motto: '',
            description: ''
        }, {
            day: 16,
            motto: '',
            description: ''
        }, {
            day: 17,
            motto: '',
            description: ''
        }, {
            day: 18,
            motto: '',
            description: ''
        }, {
            day: 19,
            motto: '',
            description: ''
        }, {
            day: 20,
            motto: '',
            description: ''
        }, {
            day: 21,
            motto: '',
            description: ''
        }, {
            day: 22,
            motto: '',
            description: ''
        }, {
            day: 23,
            motto: '',
            description: ''
        }, {
            day: 24,
            motto: '',
            description: ''
        }, {
            day: 25,
            motto: '',
            description: ''
        }, {
            day: 26,
            motto: '',
            description: ''
        }, {
            day: 27,
            motto: '',
            description: ''
        }, {
            day: 28,
            motto: '',
            description: ''
        }, {
            day: 29,
            motto: '',
            description: ''
        }, {
            day: 30,
            motto: '',
            description: ''
        }, {
            day: 31,
            motto: '',
            description: ''
        }]
    }, {
        name: 'luty',
        motto: 'inicjatywa osobista',
        days: [{
            day: 1,
            motto: '',
            description: ''
        }, {
            day: 2,
            motto: '',
            description: ''
        }, {
            day: 3,
            motto: '',
            description: ''
        }, {
            day: 4,
            motto: '',
            description: ''
        }, {
            day: 5,
            motto: '',
            description: ''
        }, {
            day: 6,
            motto: '',
            description: ''
        }, {
            day: 7,
            motto: '',
            description: ''
        }, {
            day: 8,
            motto: '',
            description: ''
        }, {
            day: 9,
            motto: '',
            description: ''
        }, {
            day: 10,
            motto: '',
            description: ''
        }, {
            day: 11,
            motto: '',
            description: ''
        }, {
            day: 12,
            motto: '',
            description: ''
        }, {
            day: 13,
            motto: '',
            description: ''
        }, {
            day: 14,
            motto: '',
            description: ''
        }, {
            day: 15,
            motto: '',
            description: ''
        }, {
            day: 16,
            motto: '',
            description: ''
        }, {
            day: 17,
            motto: '',
            description: ''
        }, {
            day: 18,
            motto: '',
            description: ''
        }, {
            day: 19,
            motto: '',
            description: ''
        }, {
            day: 20,
            motto: '',
            description: ''
        }, {
            day: 21,
            motto: '',
            description: ''
        }, {
            day: 22,
            motto: '',
            description: ''
        }, {
            day: 23,
            motto: '',
            description: ''
        }, {
            day: 24,
            motto: '',
            description: ''
        }, {
            day: 25,
            motto: '',
            description: ''
        }, {
            day: 26,
            motto: '',
            description: ''
        }, {
            day: 27,
            motto: '',
            description: ''
        }, {
            day: 28,
            motto: '',
            description: ''
        }, {
            day: 29,
            motto: '',
            description: ''
        }, {
            day: 30,
            motto: '',
            description: ''
        }, {
            day: 31,
            motto: '',
            description: ''
        }]
    }, {
        name: 'marzec',
        motto: 'zwycięska postawa',
        days: [{
            day: 1,
            motto: '',
            description: ''
        }, {
            day: 2,
            motto: '',
            description: ''
        }, {
            day: 3,
            motto: '',
            description: ''
        }, {
            day: 4,
            motto: '',
            description: ''
        }, {
            day: 5,
            motto: '',
            description: ''
        }, {
            day: 6,
            motto: '',
            description: ''
        }, {
            day: 7,
            motto: '',
            description: ''
        }, {
            day: 8,
            motto: '',
            description: ''
        }, {
            day: 9,
            motto: '',
            description: ''
        }, {
            day: 10,
            motto: '',
            description: ''
        }, {
            day: 11,
            motto: '',
            description: ''
        }, {
            day: 12,
            motto: '',
            description: ''
        }, {
            day: 13,
            motto: '',
            description: ''
        }, {
            day: 14,
            motto: '',
            description: ''
        }, {
            day: 15,
            motto: '',
            description: ''
        }, {
            day: 16,
            motto: '',
            description: ''
        }, {
            day: 17,
            motto: '',
            description: ''
        }, {
            day: 18,
            motto: '',
            description: ''
        }, {
            day: 19,
            motto: '',
            description: ''
        }, {
            day: 20,
            motto: '',
            description: ''
        }, {
            day: 21,
            motto: '',
            description: ''
        }, {
            day: 22,
            motto: '',
            description: ''
        }, {
            day: 23,
            motto: '',
            description: ''
        }, {
            day: 24,
            motto: '',
            description: ''
        }, {
            day: 25,
            motto: '',
            description: ''
        }, {
            day: 26,
            motto: '',
            description: ''
        }, {
            day: 27,
            motto: '',
            description: ''
        }, {
            day: 28,
            motto: '',
            description: ''
        }, {
            day: 29,
            motto: '',
            description: ''
        }, {
            day: 30,
            motto: '',
            description: ''
        }, {
            day: 31,
            motto: '',
            description: ''
        }]
    }, {
        name: 'kwiecień',
        motto: 'wyznaczanie celów',
        days: [{
            day: 1,
            motto: '',
            description: ''
        }, {
            day: 2,
            motto: '',
            description: ''
        }, {
            day: 3,
            motto: '',
            description: ''
        }, {
            day: 4,
            motto: '',
            description: ''
        }, {
            day: 5,
            motto: '',
            description: ''
        }, {
            day: 6,
            motto: '',
            description: ''
        }, {
            day: 7,
            motto: '',
            description: ''
        }, {
            day: 8,
            motto: '',
            description: ''
        }, {
            day: 9,
            motto: '',
            description: ''
        }, {
            day: 10,
            motto: '',
            description: ''
        }, {
            day: 11,
            motto: '',
            description: ''
        }, {
            day: 12,
            motto: '',
            description: ''
        }, {
            day: 13,
            motto: '',
            description: ''
        }, {
            day: 14,
            motto: '',
            description: ''
        }, {
            day: 15,
            motto: '',
            description: ''
        }, {
            day: 16,
            motto: '',
            description: ''
        }, {
            day: 17,
            motto: '',
            description: ''
        }, {
            day: 18,
            motto: '',
            description: ''
        }, {
            day: 19,
            motto: '',
            description: ''
        }, {
            day: 20,
            motto: '',
            description: ''
        }, {
            day: 21,
            motto: '',
            description: ''
        }, {
            day: 22,
            motto: '',
            description: ''
        }, {
            day: 23,
            motto: '',
            description: ''
        }, {
            day: 24,
            motto: '',
            description: ''
        }, {
            day: 25,
            motto: '',
            description: ''
        }, {
            day: 26,
            motto: '',
            description: ''
        }, {
            day: 27,
            motto: '',
            description: ''
        }, {
            day: 28,
            motto: '',
            description: ''
        }, {
            day: 29,
            motto: '',
            description: ''
        }, {
            day: 30,
            motto: '',
            description: ''
        }, {
            day: 31,
            motto: '',
            description: ''
        }]
    }, {
        name: 'maj',
        motto: 'Działanie',
        days: [{
            day: 1,
            motto: '',
            description: ''
        }, {
            day: 2,
            motto: '',
            description: ''
        }, {
            day: 3,
            motto: '',
            description: ''
        }, {
            day: 4,
            motto: '',
            description: ''
        }, {
            day: 5,
            motto: '',
            description: ''
        }, {
            day: 6,
            motto: '',
            description: ''
        }, {
            day: 7,
            motto: '',
            description: ''
        }, {
            day: 8,
            motto: '',
            description: ''
        }, {
            day: 9,
            motto: '',
            description: ''
        }, {
            day: 10,
            motto: '',
            description: ''
        }, {
            day: 11,
            motto: '',
            description: ''
        }, {
            day: 12,
            motto: '',
            description: ''
        }, {
            day: 13,
            motto: '',
            description: ''
        }, {
            day: 14,
            motto: '',
            description: ''
        }, {
            day: 15,
            motto: '',
            description: ''
        }, {
            day: 16,
            motto: '',
            description: ''
        }, {
            day: 17,
            motto: '',
            description: ''
        }, {
            day: 18,
            motto: '',
            description: ''
        }, {
            day: 19,
            motto: '',
            description: ''
        }, {
            day: 20,
            motto: '',
            description: ''
        }, {
            day: 21,
            motto: '',
            description: ''
        }, {
            day: 22,
            motto: '',
            description: ''
        }, {
            day: 23,
            motto: '',
            description: ''
        }, {
            day: 24,
            motto: '',
            description: ''
        }, {
            day: 25,
            motto: '',
            description: ''
        }, {
            day: 26,
            motto: '',
            description: ''
        }, {
            day: 27,
            motto: '',
            description: ''
        }, {
            day: 28,
            motto: '',
            description: ''
        }, {
            day: 29,
            motto: '',
            description: ''
        }, {
            day: 30,
            motto: '',
            description: ''
        }, {
            day: 31,
            motto: '',
            description: ''
        }]
    }, {
        name: 'czerwiec',
        motto: 'Okazje',
        days: [{
            day: 1,
            motto: 'okazja ma dziwny sposób podkradania się do osoby, która potrafi ją rozpoznać i jest gotowa z niej skorzystać',
            description: 'Dziwnym kaprysem ludzkiej natury niektórzy z nas potrafią dostrzec okazje, podczas gdy inni widzą jedynie problemy. kKiedy trenujesz umysł w pposzukiwaniu sposobności, to przekonujesz się, że dosłownie każdy dzień przynosi więcej okazji, niż możesz wykożystać. Będą wszędzie wokół ciebie. Nie Ty będziesz wypatrywał, to one będą szukać ciebie. Największy problem stworzy wybór najlepszych.'
        }, {
            day: 2,
            motto: 'ci, którzy łatwo widzą swoje ograniczenia, zazwyczaj z trudem dostrzegają okazje',
            description: 'Producent filmowy, Michael Todd, powiedział kiedyś: "Być bez grosza to sytuacja chwilowa; być biednym to stan umysłu". Podobnie jest z okazjami. To, czy zauważasz sposobności czy ograniczenia, leży całkowicie w zasięgu twojej kontroli. Sposób postrzegania świata stanowi odbicie odbicie twojej postawy umysłowej. Jeżeli koncentrujesz się na swojej niezdatności - dręczą cię strach, wątpliwości i porażki, kiedy jednak skupiasz się swych mocnych stronach - odnajdujesz odwagę, pewność i sukces.<br>Pewność siebie może zastąpić powątpiewanie o sobie jedynie w wyniku celowego, zaplanowanego wysiłku. Kiedy zaczniesz wątpić w swoje umiejętności i zdolności, zatrzymaj się, by przejrzeć wcześniejsze dokonania. Zidentyfikuj każde doświadczenie, mogące pomóc w obecnej sytuacji. Gdy zastosujesz wiedzę i mądrość, jakie zgromadziłeś, niewiele pozostanie ograniczeń, których nie będziesz mógł pokonać.'
        }, {
            day: 3,
            motto: 'nie twierdz, że świat nie dał ci okazji',
            description: 'Okazje nigdy nie są tak zwyczajnie wręczane przez los; muszą zostać wykreowane. Dla wszystkich ludzi dowolny okres życia obfituje w okazje. Mogą się one nie mieścić w kręgu twych preferencji, ale każda wykorzystana sposobność prowadzi do większych i lepszych okazji. Ułomności fizyczne czy umysłowe mogą wymagać badania tetytorium nieznanego dla innych, jednak równocześnie oznacza to, że posiadasz sposobności, których pozostali nigdy nie odnajdą. Pomyśl o błyskotliwej rozprawie Stephena Hawkinga na temat natury wszechświata, mimo faktu że paraliż uniemożliwia mu pisanie i mówienie w takiej postaci, jaką my znamy.<br>Ci, którzy podchodzą do swojej pracy i kariery z entuzjazmem, zawsze znajdują mnóstwo okazji, podczas gdy ci, którzy narzekają, że nikt nie dał im nigdy szansy, są zaledwie obserwatorami życia. Kiedy postanowisz, że nie dasz nikomu decydować za ciebie o twojej przyszłości, kiedy odmawiasz chwilowym niepowodzeniom prawa do pokonania cię, twoim przeznaczeniem staje się wielki sukces. Sposobności będą na ciebie czekać.'
        }, {
            day: 4,
            motto: '',
            description: ''
        }, {
            day: 5,
            motto: '',
            description: ''
        }, {
            day: 6,
            motto: '',
            description: ''
        }, {
            day: 7,
            motto: '',
            description: ''
        }, {
            day: 8,
            motto: '',
            description: ''
        }, {
            day: 9,
            motto: '',
            description: ''
        }, {
            day: 10,
            motto: '',
            description: ''
        }, {
            day: 11,
            motto: '',
            description: ''
        }, {
            day: 12,
            motto: '',
            description: ''
        }, {
            day: 13,
            motto: '',
            description: ''
        }, {
            day: 14,
            motto: '',
            description: ''
        }, {
            day: 15,
            motto: '',
            description: ''
        }, {
            day: 16,
            motto: '',
            description: ''
        }, {
            day: 17,
            motto: '',
            description: ''
        }, {
            day: 18,
            motto: '',
            description: ''
        }, {
            day: 19,
            motto: '',
            description: ''
        }, {
            day: 20,
            motto: '',
            description: ''
        }, {
            day: 21,
            motto: '',
            description: ''
        }, {
            day: 22,
            motto: '',
            description: ''
        }, {
            day: 23,
            motto: '',
            description: ''
        }, {
            day: 24,
            motto: '',
            description: ''
        }, {
            day: 25,
            motto: 'pokaż mi, jak zaoszczędzić drobną kwotę na dowolnej operacji w fabryce, a pokażę ci, jak zdobyć szybki i odpowiedni awans',
            description: 'Kiedy poszukujesz sposobów zaoszczędzenia pieniędzy dla firmy, postępujesz jak kierownik lub właściciel. Każdy kierownik wart swej płacy wie, że w produkcji seryjnej zaoszczędzenie kilku groszy w dowolnym procesie szybko zsumuje się do milionów. A ktoś, kto wymyśli sposób na zaoszczędzenie przez firmę milionów jest "skazany na awans". Jest po prostu zbyt cenny, by nie awansował.<br>Najlepszą osobą, która może poprawić wydajność w twojej pracy, jesteś ty sam. Nikt inny nie zna jej tak dokładnie jak ty. Zachęć siebie do stałego ulepszania poprzez rywalizowanie z sobą samym. Wykonująć konkretne zadanie szukaj skrótów, które pozwolą ci ukończyć je szybciej. Czas, jaki zaoszczędzisz, wykorzystaj na przeanalizowanie innych części swej pracy, zgłoszenie się do pomocy przy trudnych czy czasochłonnych operacjach albo podjęcie się nowego, bardziej satysfakcjonującego zadania.'
        }, {
            day: 26,
            motto: 'wielu ludzi sukcesu w porażce i przeciwności odnalazło okazje, których nie rozpoznałoby w bardziej korzystnych okolicznościach',
            description: 'Samuel Johnson zauważył kiedyź, że perspektywa śmierci na szubienicy cudownie wyostrza umysł. prawdopodobnie mogłeś sam odkryć, że twój umysł wydaje się najbardziej bystry, kiedy mierzysz się z największymi trudnościami. Desperacja często dowodzi, że w rzeczywistości jesteś lepszy niż myslisz. Za wyjątkiem jednak bezpośredniego zagrożenia twojego życie czy zdrowia, mało jest sytuacji, które wymagają natychmiastowego działania. Kiedy świat zdaje się spiskować przeciw tobie i nic się nie udaje, przerwij na chwilę, aby przemyśleć sytuację - potem opracuj najbardziej odpowiedni plan działania, ten, który ma największe prawo powodzenia.'
        }, {
            day: 27,
            motto: 'nie przeoczaj drobnych szczegółów; pamiętaj, że wszechświat i wszystko, co się w nim znajduje, jest zbudowane z maleńkich atomów',
            description: 'Stare powiedzenie mówi: "Jeśli zadbasz o szczegóły, wielkie sprawy zatroszczą się same o siebie". Innymi słowy, każda praca składa się z małych detali, z których każdy, jeśli zostanie przeoczony, może stwarzać później wielkie problemy. Jeżeli masz kłopoty z radzeniem sobie ze szczegółami - robotą papierkową, księgowaniem rachunków i innymi nużącymi drobiazgami - w cyklu swej pracy wyznacz czas (dziennie, tygodniowo czy miesięcznie), by zająć się tymi mało pociągającymi czynnościami. Przygotuj się umysłowo do owych zadań, a może nawet uznasz, iż ta praca nie była ani trochę tak nieprzyjemna jak się spodziewałeś.'
        }, {
            day: 28,
            motto: 'twoja praca nie zrobi dla ciebie więcej, niż ty dla niej',
            description: 'Każda praca zawiera okazje do osobistego wzrostu, jeśli podchodzisz do niej jako do pozytywnego doświadczenia, które uczy. Podobnie jak każde przedsięwzięcie trzeba przystosować do nowych technologii, nowej konkurencjii i niezliczonych innych zmian, tak samo musi to robić każdy człowiek. Jeżeli w swojej pracy nie uczysz się i nie robisz postępów, to następuje stagnacja i zostajesz w tyle.<br>Nie można stać w miejscu. Patrz na każdy dzień jako na okazję nauczenia się czegoś nowego, udoskonalenia siebie, a potem zrób coś lepiej niż kiedykolwiek przedtem. W dynamicznej formie nie da się opanować po mistrzowsku każdego dnia. Właśnie wtedy, kiedy sądzisz że wszystko rozgryzłeś, rzeczy ulegają zmianie. Przyjmij takie zmiany jako konieczny aspekt biznesu, który czyni życie ciekawszym i pasjonującym. Uznasz swą pracę za znacznie przyjemniejszą. kiedy tak postąpisz i naprawdę przekonaz się, że robi ona dla ciebie więcej niż ty dla niej.'
        }, {
            day: 29,
            motto: 'zdolności są czymś wspanilszym od pieniędzy, ponieważ nie mogą zostać zgubione ani skradzione',
            description: 'Kiedy studiujesz życie ludzi, którzy odnieśli bardzo duży sukces, spostrzeżesz, że rzadko wspinnają się na szczyt i pozostają tam. Często kilka razy podczas swojej kariery wdrapują się na wierzchołek i spadają na dno, wiedzą jednak, iż to, co wyniosło ich tam, gdzie byli - ich zdolności - istnieje nadal, by pomóc im raz jeszcze sięgnąć szczytu.<br>Twoje umiejętności to jedyna rzecz, którą masz na swoją wyłączną własność; nikt nigdy nie może cię ich pozbawić.'
        }, {
            day: 30,
            motto: 'kiedy zamykasz drzwi swego umysłu przed negatywnymi myślami, otwierają się przed tobą bramy okazji',
            description: 'Naturą wszystkich okazji jest to, że po prostu nie chcą przyłączać się do negatywnych myślicieli. Negatywne umysły nie potrafią wymyślić pasjonujących nowych przedsięwzięć, wynaleźć nowych produktów, rozwinąć trudnych problemów ani też stworzyć pięknej muzyki czy dzieła sztuki. wszystkie te formy aktywności wymagają pozytywnej wiary w siebie i swoje zdolności.<br>Kiedy do każdego wyzwania podchodzisz z pozytywną postawą umysłową, zawsze odkryjesz okazje, które inni przeoczyli. Rozkoszuj się swymi osiągnięciami, smakuj je i przypominaj sobie o nich, kiedy droga staje się trudna. Czerp otuchę i pocieszenie ze świadomości, że powiodło ci się w przeszłości i że może tak być ponownie. <b>Możes to zrobić, jeżli myślisz, że możesz!</b>'
        }]
    }, {
        name: 'lipiec',
        motto: 'moc pracy zespołowej',
        days: [{
            day: 1,
            motto: 'jeśli nie jesteś oficerem w wojsku, lepsze rezultaty uzyskasz prosząc niż rozkazując',
            description: 'Armie spędzają niezliczone godziny na ćwiczeniu ludzi w wykonywaniu rozkazów bez zadawania pytań. W przypadku żołnieża to ważna zaleta. Jednak w życiu codziennym sprawy nie funkcjonują w taki sposób. Liderzy w biznesie, polityce i samorządzie wiedzą, że zwykli ludzie będą dokonywać wyjątkowych dzieł, kiedy zostaną o to poproszeni - a nie kiedy rozkaże im się to zrobić.<br>Nawet kierując ludźmi, uzyskasz znacznie więcej, kiedy zastąpisz każde polecenie prośbą. Zwroty grzecznościowe takie jak: Czy zechciałbyć... albo czy mógłbym prosić o pańską pomoc w... czy też zawsze skuteczne Proszę... znacznie częściej przyniosą dobry skutek, niż onieśmielanie tych, którzy dla ciebie pracują. Kiedy zaś potrzebujesz pomocy ze stronyc tych, na których pensję nie masz wpływu, przekonasz się, że także dużo lepiej reagują na prośby niż polecenia.'
        }, {
            day: 2,
            motto: 'nikt nie jest zdolny do wydawania poleceń, dopóki sam nie nauczy się, jak przyjmować i wykonywać instrukcje',
            description: 'Istotną zaletą przywództwa jest rozwijanie zdolności przekonywania innych, aby wiązali swoje cele z twoimi i z celami firmy. Dopóki ty sam nie jesteś w stanie połączyć sił z innymi w dążeniu do wspólnego celu, nigdy nie przekonasz innych, aby przyłączyli się do twego. Skuteczni liderzy uznają wartość wspólnej pracy i uczą się, jak wykonywać instrukcje, zanim przyjmą odpowiedzialość za postępowanie innych.<br>Dobrzy przywódcy pokazują swoim przykładem, jakiego postępowania oczekują od innych. Nawet jeśli oddziały wojskowe są wyszkolone do niekwestionowanego wykonywania rozkazów, to i tak oficer prowadzi ich do walki. Nie możesz innych popychać, by naśladowali twój przykład; musisz pociągnąć ich za sobą. Kiedy poprzez każde swoje słowo i czyn udowadniasz, że jesteś człowiekiem z charakterem, który pracuje dla wyższego dobra całej instytucji, twoi ludzie podążą za tobą.'
        }, {
            day: 3,
            motto: 'chętna współpraca wytwarza trwałą moc, podczas gdy wymuszona kończy się klęską',
            description: 'Nigdy nie przetrwała żadna cywilizacja oparta o niesprawiedliwe traktowanie ludzi. Tyran może wymusić współpracę przez jakiś czas, ale tego rodzaju siła nigdy nie jest długotrwała. Tylko wtedy, kiedy ludzi obdarza się szacunkiem, na jakizasługują, chętnie stwarzają i utrzymują udane instytucje i społeczeństwa. Budując firmę czy organizację opartą na zasadach uczciwości i sprawiedliwości w stosunku do każdego członka, inicjujesz siłę, która długo przetrwa.<br>Najlepszym sposobem zapewnienia sobie zaangażowania i nie ustającej współpracy jest zwyczajne stosowanie złotej reguły. To najbardziej udana i trwała teoria zarządzania, jaką kiedykolwiek wymyślono. Kiedy traktujesz innych tak, jak chciałbyś być traktowany będąc na ich miejscu, zachęcasz do lojalności i entuzjastycznej współpracy. Wyznaczaj wysokie normy dla siebie i innych, traktuj ich dobrze, pozwól im wykonywać ich zajęcia, a będą dla ciebie dokonywać cudów.'
        }, {
            day: 4,
            motto: 'staraj się mówić swojemu szefowi o tym, co lubisz, a przekonasz się, jak chętnie pomoże ci pozbyć się tego, co ci nie odpowiada',
            description: 'W ostatnich latach poczyniono wielki postępy w przezwyciężaniu tradycyjnych animozji pomiędzy pracownikami i szefami. Wreszcie dotarło do nas, że kiedy skupiamy się na lepszym obsługiwaniu klientów i kontrachentów, wszyscy wygrywają. Gdy zaczniesz się koncentrować na tym, co ci się nie podoba, zdziwi cię, jak szybko zostanie ci powierzona większa odpowiedzialność i będziesz mógł uczyć swycj pracowników wykonywania twojej wcześniejszej pracy.'
        }, {
            day: 5,
            motto: 'na dowolnym rynku przyjazna współpraca zdobędzie dla ciebie znacznie więcej niż nieprzyjazna agitacja',
            description: 'Kiedy traktujesz swoich konkurentów z uprzejmością i szacunkiem, jakich sam pragniesz, większość z nich odpowie w ten sam sopsób i w rezultaciepowstanie stabilny, wydajny i zyskowny interes. Z drugiej strony przemysł czy rynek, składający się z zawistnych, niemoralnych rywali, wkrótce zniszczy sam siebie. Kiedy ktoś pyta cię, jak twoje produkty i usługi wyglądają w porównaniu z konkurentami, mów o swych rywalach uprzejmie i z szacunkiem, ale wykorzystuj pytania, by skierować dyskusję na własną firmę i produkty. Przyznaj innym dobre strony, a potem przystąp do działania. Jeśli zbytnio utyskujesz na konkurencję, potencjalni klienci mogą się zastanawiać, co tracą i nie chcieć zawierać transakcji, dopóki nie porównają twoich produktów i usług z innymi.'
        }, {
            day: 6,
            motto: 'nikt nie może odnieść i utrzymać sukcesu bez przyjaznej współpracy z innymi',
            description: 'W dzisiejszym, powiązanym zależnościami społeczeństwie, w żadnym biznesie, zawodzie czy zajęciu praktycznie niemożliwe jest, by jednostka sięgała po szczyty sukcesu bez pomocy innych. Najlepszym sposobem syskania przyjaznej współpracy jest ofiarowanie jej. Kiedy masz w zwyczaju możliwie najczęstsze zachęcanie innych i pomaganie im w robieniu kariery, to większość z nich odwzajemni się, gdy sam będziesz potrzebował pomocy. Dawaj szczodrze, a na pewno przyniesie ci to pożytek.'
        }, {
            day: 7,
            motto: 'współpraca w zakładzie musi się rozpocząć od wierzchołka, jeśli ma się pojawić na dowolnych szczeblach - to samo dotyczy wydajności',
            description: 'W większości dużych instytucji ilość czasu i energii marnowanej na rywalizację pomiędzy oddziałami jest ogromna. Kierownicy rywalizujący z innymi wewnątrz firmy trwonią cenne zasoby, które powinny być skierowane ku spełnieniu misji firmy, jaką jest lepsze służenie klienteli. Co gorsze, negatywna, wewnętrzna koncentracja może powodować utratę sposobności, której pełny skutek ujawni się dopiero po miesiącach czy nawet latach. Niezależnie od tego, czy jesteś szefem oddziału, czy najmłodszym pracownikiem, możesz niezmiernie pomóc swojej firmie poprzez odmowę udziału w wewnętrznych walkach. Zamiast konkurować z innymi, rywalizuj sam ze sobą, aby wykonać pracę najlepiej jak potrafisz.'
        }, {
            day: 8,
            motto: 'przyjazna współpraca nie należy do dzieł szatana; on pracuje po przeciwnej stronie',
            description: 'Najbardziej szlacetne spośród ludzkich relacji zostały ukształtowane w duchu współpracy i harmonii. Współpraca na wiele sposobów jest fizycznym wyrazem twojej dbałości i troski o kolegów. Kiedy pracujesz z innymi w duchu przyjaznej współpracy, zachowujesz się zgodnie z podstawowymi zasadami większości religii i wszystkich udanych społeczeństw. Każdy czuje czasami targanie zazdrości i zawiści, któremu zwykle towarzyszy impuls do przysporzenia problemów lub kłopotów ludziom nielubianym. Prawdziwi jednak ludzie sukcesu nauczyli się powściągać takie odruchy. Wiedzą, że jeśli skoncentrują się na własnych celach i po drodze pomogą innym, to w końcu osiągną swoje zamierzenia. Nie jest łatwo zawsze być osobą przyjacielską i współpracującą, jednak w końcu przekonujemy się, że jest to warte wysiłku.'
        }, {
            day: 9,
            motto: 'przyjazna współpraca zawsze się opłaca, ponieważ tworzy wśród członków zespołu pozytywną postawę umysłową, która nie uznaje przeciwności',
            description: 'W każdym zorganizowanym przedsięwzięciu występują przeciwności. Czasem pojawiają się jako problemy techniczne; czasem są nieporozumieniem pomiędzy członkami zespołu co do szlaku, którym najlepiej pójść. Jeżeli dawałeś przykład inicjatywy i otwartego porozumiewania się, to okaże się, że twój zespół posiada zasoby umysłowe i duchowe, by przezwyciężyć tego typu walki.<br>Grupa ludzi, którzy wietzą swemu przywódcy i sobie nawzajem, nie będzie tracić energii, aby wygrać prestiż dla siebie. Wiedzą, że wszyscy skorzystają z rozwiązania i mają motywację, by znaleźć je, dzieląc się wiedzą i pomysłami. Z tych wielu elementów wprawny lider potrafi stworzyć konieczne rozwiązanie, jednak tylko wtedy, kiedy zwycięży duch przyjaźni i uczciwości.'
        }, {
            day: 10,
            motto: 'ci, którzy nie potrafią przyjmować z wdzięcznością poleceń, nie mają po co ich wydawać',
            description: 'Jeżeli jesteś lekkomyślnym czy kłótliwym pracownikiem, który nie potrafi przyjmować poleceń od innych, to twoim przeznaczeniem jest pozostanie na samym dole sił wytwórczych. Zanim będziesz mógł liczyć na przewodzenie innym ludziom, musisz nauczyć się skutecznie kierować samym sobą i swymi związkami z ludźmi, szczególnietymi na wyższych stanowiskach w firmie. Dopóki nie posiądziesz sztuki opanowywania swych relacji z własnym szefem czy szefami, nigdy nie będziesz w stanie zarządzać związkami z podwładnymi.'
        }, {
            day: 11,
            motto: 'pamiętaj, że nikt nie może zranić twoich uczuć bez twojej współpracy i przyzwolenia',
            description: 'Nikt nie może wywołać w tobie żadnej reakcji emocjonalnej, jeśli najpierw nie dasz mu na to pozwolenia. Tylko ty jesteś odpowiedzialny za swoje uczucie i emocje. Kiedy wiesz, co zamierzasz zrobić ze swoim życiem, nie pozwolisz, by męczące sytuacje na długo odciągnęły cię od twego celu. Jeśli wyznaczasz sobie ambitne cele i entuzjastycznie pracujesz dla niech, szybko zrozumiesz, że szkoda czasu na to, by pozwolić drobnym przykrościom przygnębiać cię i odwodzić od celu.'
        }, {
            day: 12,
            motto: 'jeśli odwiedzasz przyjaciół tylko wtedy, kiedy od nich czegoś potrzebujesz, wkrótce znajdziesz się bez przyjaciół',
            description: 'Jest wiele mądrości w starym powiedzeniu: "Jeśli pragniesz przyjaciół, bądź przyjacielem". Przyjaźć oznacza dawanie bez spodziewania się czegokolwiek w zamian. Zajęci ludzie sukcesu nie poszukują nowych znajomych. Jeśli chcesz stać się ich przyjacielem, musisz podjąć wysiłek, by się z nimi zaprzyjaźnić. Pozwól im poznać, że interesują cię jako ludzie, że nie zajmuje cię, co mogą dla ciebie zrobić, a może się okazać, iż zyskałeś prawdziwych i oddanych przyjaciół.'
        }, {
            day: 13,
            motto: 'do przyjaźni trzeba dorastać, a nie traktować jej za oczywistość',
            description: 'Twoi przyjaciele będą tym, kim ich uczynisz. Jeśli chętnie ofiarowujesz swój czas i zawsze okazujesz wrażliwość na innych, to twoi przyjaciele staną się uprzejmi i wspaniałomyślni. Jeżeli jesteś osobą, która przyjmuje istnienie przyjaciół za oczywistość, niewiele dając i nie oczekując w zamian, będziesz przyciągał przyjaciół przejawiających te same cechy. W przyjaźni podobieństwa się przyciągają.<br>Od czasu do czasu oceniaj swoje zachowanie, aby określić, do jakiego typu przyjaciół się zaliczasz. Czy przypominasz osobę, którą sam chciałbyś mieć za przyjaciela? Czy chętnie dajesz więcej niż spodziewasz się w zamian, czy też wciąż prosisz, a nigdy nie obdarowujesz? czy poświęcasz czas na to, by utrzymywać kontakt i pamiętać o różnych specjalnych okazjach przyjaciela? Kiedy zaczynasz być tak pochłonięty własnymi interesami, że zaopminasz o przyjaciołach, jesteś na najlepszej drodze pozostania bez przyjaciół.'
        }, {
            day: 14,
            motto: 'Jeżeli pragniesz znajomości bądź bogaty; jeśli zależy ci na przyjaźni, bądź przyjacielem',
            description: 'Nic tak jak pieniądze nie czyni cię atrakcyjnym i pociągającym dla innych. Jednak ludzie, których przyciągado ciebie tylko to, co możesz dla nich zrobić, stają się znajomymi, nie przyjaciółmi. Jeżeli zdobędziesz bogactwo, zyskasz wielu znajomych, ale nigdy nie będziesz miał prawdziwych przyjaciół, jeśli sam nei jesteś dla innych przyjacielem. Bądź bardzo ostrożny i selektywny w dobieraniu przyjaciół. Decyduj, by otaczać się pozytywnymi ludźmi, którzy lubią cię takiego, jakim jesteś i zachęcają, byś był sobą, i to najlpeszym jak potrafisz.'
        }, {
            day: 15,
            motto: '',
            description: ''
        }, {
            day: 16,
            motto: '',
            description: ''
        }, {
            day: 17,
            motto: '',
            description: ''
        }, {
            day: 18,
            motto: '',
            description: ''
        }, {
            day: 19,
            motto: '',
            description: ''
        }, {
            day: 20,
            motto: '',
            description: ''
        }, {
            day: 21,
            motto: '',
            description: ''
        }, {
            day: 22,
            motto: '',
            description: ''
        }, {
            day: 23,
            motto: '',
            description: ''
        }, {
            day: 24,
            motto: '',
            description: ''
        }, {
            day: 25,
            motto: '',
            description: ''
        }, {
            day: 26,
            motto: '',
            description: ''
        }, {
            day: 27,
            motto: '',
            description: ''
        }, {
            day: 28,
            motto: '',
            description: ''
        }, {
            day: 29,
            motto: '',
            description: ''
        }, {
            day: 30,
            motto: '',
            description: ''
        }, {
            day: 31,
            motto: '',
            description: ''
        }]
    }, {
        name: 'sierpień',
        motto: 'klęska i porażka',
        days: [{
            day: 1,
            motto: '',
            description: ''
        }, {
            day: 2,
            motto: '',
            description: ''
        }, {
            day: 3,
            motto: '',
            description: ''
        }, {
            day: 4,
            motto: '',
            description: ''
        }, {
            day: 5,
            motto: '',
            description: ''
        }, {
            day: 6,
            motto: '',
            description: ''
        }, {
            day: 7,
            motto: '',
            description: ''
        }, {
            day: 8,
            motto: '',
            description: ''
        }, {
            day: 9,
            motto: '',
            description: ''
        }, {
            day: 10,
            motto: '',
            description: ''
        }, {
            day: 11,
            motto: '',
            description: ''
        }, {
            day: 12,
            motto: '',
            description: ''
        }, {
            day: 13,
            motto: '',
            description: ''
        }, {
            day: 14,
            motto: '',
            description: ''
        }, {
            day: 15,
            motto: '',
            description: ''
        }, {
            day: 16,
            motto: '',
            description: ''
        }, {
            day: 17,
            motto: '',
            description: ''
        }, {
            day: 18,
            motto: '',
            description: ''
        }, {
            day: 19,
            motto: '',
            description: ''
        }, {
            day: 20,
            motto: '',
            description: ''
        }, {
            day: 21,
            motto: '',
            description: ''
        }, {
            day: 22,
            motto: '',
            description: ''
        }, {
            day: 23,
            motto: '',
            description: ''
        }, {
            day: 24,
            motto: '',
            description: ''
        }, {
            day: 25,
            motto: '',
            description: ''
        }, {
            day: 26,
            motto: '',
            description: ''
        }, {
            day: 27,
            motto: '',
            description: ''
        }, {
            day: 28,
            motto: '',
            description: ''
        }, {
            day: 29,
            motto: '',
            description: ''
        }, {
            day: 30,
            motto: '',
            description: ''
        }, {
            day: 31,
            motto: '',
            description: ''
        }]
    }, {
        name: 'wrzesień',
        motto: 'dodatkowy tysiąc kroków',
        days: [{
            day: 1,
            motto: '',
            description: ''
        }, {
            day: 2,
            motto: '',
            description: ''
        }, {
            day: 3,
            motto: '',
            description: ''
        }, {
            day: 4,
            motto: '',
            description: ''
        }, {
            day: 5,
            motto: '',
            description: ''
        }, {
            day: 6,
            motto: '',
            description: ''
        }, {
            day: 7,
            motto: '',
            description: ''
        }, {
            day: 8,
            motto: '',
            description: ''
        }, {
            day: 9,
            motto: '',
            description: ''
        }, {
            day: 10,
            motto: '',
            description: ''
        }, {
            day: 11,
            motto: '',
            description: ''
        }, {
            day: 12,
            motto: '',
            description: ''
        }, {
            day: 13,
            motto: '',
            description: ''
        }, {
            day: 14,
            motto: '',
            description: ''
        }, {
            day: 15,
            motto: '',
            description: ''
        }, {
            day: 16,
            motto: '',
            description: ''
        }, {
            day: 17,
            motto: '',
            description: ''
        }, {
            day: 18,
            motto: '',
            description: ''
        }, {
            day: 19,
            motto: '',
            description: ''
        }, {
            day: 20,
            motto: '',
            description: ''
        }, {
            day: 21,
            motto: '',
            description: ''
        }, {
            day: 22,
            motto: '',
            description: ''
        }, {
            day: 23,
            motto: '',
            description: ''
        }, {
            day: 24,
            motto: '',
            description: ''
        }, {
            day: 25,
            motto: '',
            description: ''
        }, {
            day: 26,
            motto: '',
            description: ''
        }, {
            day: 27,
            motto: '',
            description: ''
        }, {
            day: 28,
            motto: '',
            description: ''
        }, {
            day: 29,
            motto: '',
            description: ''
        }, {
            day: 30,
            motto: '',
            description: ''
        }, {
            day: 31,
            motto: '',
            description: ''
        }]
    }, {
        name: 'październik',
        motto: 'Twój umysł',
        days: [{
            day: 1,
            motto: '',
            description: ''
        }, {
            day: 2,
            motto: '',
            description: ''
        }, {
            day: 3,
            motto: '',
            description: ''
        }, {
            day: 4,
            motto: '',
            description: ''
        }, {
            day: 5,
            motto: '',
            description: ''
        }, {
            day: 6,
            motto: '',
            description: ''
        }, {
            day: 7,
            motto: '',
            description: ''
        }, {
            day: 8,
            motto: '',
            description: ''
        }, {
            day: 9,
            motto: '',
            description: ''
        }, {
            day: 10,
            motto: '',
            description: ''
        }, {
            day: 11,
            motto: '',
            description: ''
        }, {
            day: 12,
            motto: '',
            description: ''
        }, {
            day: 13,
            motto: '',
            description: ''
        }, {
            day: 14,
            motto: '',
            description: ''
        }, {
            day: 15,
            motto: '',
            description: ''
        }, {
            day: 16,
            motto: '',
            description: ''
        }, {
            day: 17,
            motto: '',
            description: ''
        }, {
            day: 18,
            motto: '',
            description: ''
        }, {
            day: 19,
            motto: '',
            description: ''
        }, {
            day: 20,
            motto: '',
            description: ''
        }, {
            day: 21,
            motto: '',
            description: ''
        }, {
            day: 22,
            motto: '',
            description: ''
        }, {
            day: 23,
            motto: '',
            description: ''
        }, {
            day: 24,
            motto: '',
            description: ''
        }, {
            day: 25,
            motto: '',
            description: ''
        }, {
            day: 26,
            motto: '',
            description: ''
        }, {
            day: 27,
            motto: '',
            description: ''
        }, {
            day: 28,
            motto: '',
            description: ''
        }, {
            day: 29,
            motto: '',
            description: ''
        }, {
            day: 30,
            motto: '',
            description: ''
        }, {
            day: 31,
            motto: '',
            description: ''
        }]
    }, {
        name: 'listopad',
        motto: 'zdrowie i szczęście',
        days: [{
            day: 1,
            motto: '',
            description: ''
        }, {
            day: 2,
            motto: '',
            description: ''
        }, {
            day: 3,
            motto: '',
            description: ''
        }, {
            day: 4,
            motto: '',
            description: ''
        }, {
            day: 5,
            motto: '',
            description: ''
        }, {
            day: 6,
            motto: '',
            description: ''
        }, {
            day: 7,
            motto: '',
            description: ''
        }, {
            day: 8,
            motto: '',
            description: ''
        }, {
            day: 9,
            motto: '',
            description: ''
        }, {
            day: 10,
            motto: '',
            description: ''
        }, {
            day: 11,
            motto: '',
            description: ''
        }, {
            day: 12,
            motto: '',
            description: ''
        }, {
            day: 13,
            motto: '',
            description: ''
        }, {
            day: 14,
            motto: '',
            description: ''
        }, {
            day: 15,
            motto: '',
            description: ''
        }, {
            day: 16,
            motto: '',
            description: ''
        }, {
            day: 17,
            motto: '',
            description: ''
        }, {
            day: 18,
            motto: '',
            description: ''
        }, {
            day: 19,
            motto: '',
            description: ''
        }, {
            day: 20,
            motto: '',
            description: ''
        }, {
            day: 21,
            motto: '',
            description: ''
        }, {
            day: 22,
            motto: '',
            description: ''
        }, {
            day: 23,
            motto: '',
            description: ''
        }, {
            day: 24,
            motto: '',
            description: ''
        }, {
            day: 25,
            motto: '',
            description: ''
        }, {
            day: 26,
            motto: '',
            description: ''
        }, {
            day: 27,
            motto: '',
            description: ''
        }, {
            day: 28,
            motto: '',
            description: ''
        }, {
            day: 29,
            motto: '',
            description: ''
        }, {
            day: 30,
            motto: '',
            description: ''
        }, {
            day: 31,
            motto: '',
            description: ''
        }]
    }, {
        name: 'grudzień',
        motto: 'wiara i nadzieja',
        days: [{
            day: 1,
            motto: '',
            description: ''
        }, {
            day: 2,
            motto: '',
            description: ''
        }, {
            day: 3,
            motto: '',
            description: ''
        }, {
            day: 4,
            motto: '',
            description: ''
        }, {
            day: 5,
            motto: '',
            description: ''
        }, {
            day: 6,
            motto: '',
            description: ''
        }, {
            day: 7,
            motto: '',
            description: ''
        }, {
            day: 8,
            motto: '',
            description: ''
        }, {
            day: 9,
            motto: '',
            description: ''
        }, {
            day: 10,
            motto: '',
            description: ''
        }, {
            day: 11,
            motto: '',
            description: ''
        }, {
            day: 12,
            motto: '',
            description: ''
        }, {
            day: 13,
            motto: '',
            description: ''
        }, {
            day: 14,
            motto: '',
            description: ''
        }, {
            day: 15,
            motto: '',
            description: ''
        }, {
            day: 16,
            motto: '',
            description: ''
        }, {
            day: 17,
            motto: '',
            description: ''
        }, {
            day: 18,
            motto: '',
            description: ''
        }, {
            day: 19,
            motto: '',
            description: ''
        }, {
            day: 20,
            motto: '',
            description: ''
        }, {
            day: 21,
            motto: '',
            description: ''
        }, {
            day: 22,
            motto: '',
            description: ''
        }, {
            day: 23,
            motto: '',
            description: ''
        }, {
            day: 24,
            motto: '',
            description: ''
        }, {
            day: 25,
            motto: '',
            description: ''
        }, {
            day: 26,
            motto: '',
            description: ''
        }, {
            day: 27,
            motto: '',
            description: ''
        }, {
            day: 28,
            motto: '',
            description: ''
        }, {
            day: 29,
            motto: '',
            description: ''
        }, {
            day: 30,
            motto: '',
            description: ''
        }, {
            day: 31,
            motto: '',
            description: ''
        }]
    }]
}
